# .github/actions/generate-test-secrets/action.yml
#
# Generates random secrets for container testing
#
name: 'Generate Test Secrets'
description: 'Generates random secrets for OCI container test runs'

outputs:
  session_secret:
    description: 'Random session secret'
    value: ${{ steps.generate.outputs.session_secret }}
  hmac_secret:
    description: 'Random HMAC secret'
    value: ${{ steps.generate.outputs.hmac_secret }}
  secret:
    description: 'Random secret'
    value: ${{ steps.generate.outputs.secret }}

runs:
  using: 'composite'
  steps:
    - name: Generate random secrets
      id: generate
      shell: bash
      run: |
        # Generate cryptographically secure random secrets
        SESSION_SECRET=$(openssl rand -hex 32)
        HMAC_SECRET=$(openssl rand -hex 32)
        SECRET=$(openssl rand -hex 32)

        # Export to environment for subsequent steps
        echo "SESSION_SECRET=$SESSION_SECRET" >> $GITHUB_ENV
        echo "HMAC_SECRET=$HMAC_SECRET" >> $GITHUB_ENV
        echo "SECRET=$SECRET" >> $GITHUB_ENV

        # Also set as outputs for explicit usage
        echo "session_secret=$SESSION_SECRET" >> $GITHUB_OUTPUT
        echo "hmac_secret=$HMAC_SECRET" >> $GITHUB_OUTPUT
        echo "secret=$SECRET" >> $GITHUB_OUTPUT

        echo "Generated random secrets for container testing"
