# lib/tasks/init.rake
#
# frozen_string_literal: true

require 'securerandom'
require_relative '../onetime/key_derivation'

# Env file helpers for secret initialization.
# Delegates HKDF derivation to Onetime::KeyDerivation (single source of truth).
module OTSInit
  # Independent secrets (ADR-008 Category 2): generated with SecureRandom,
  # NOT derived from SECRET. Must be backed up individually.
  INDEPENDENT_SECRETS      = %w[AUTH_SECRET ARGON2_SECRET ACCOUNT_ID_SECRET].freeze
  # 32 bytes = 256 bits of entropy for independent secrets
  INDEPENDENT_SECRET_BYTES = 32

  def self.read_env(path)
    return {} unless File.exist?(path)

    pairs = {}
    File.readlines(path, chomp: true, encoding: 'UTF-8').each do |line|
      next if line.strip.empty? || line.start_with?('#')

      key, value = line.split('=', 2)
      next unless key && value

      pairs[key.strip] = value.strip.gsub(/\A["']|["']\z/, '')
    end
    pairs
  end

  # SECRET-verifier task helpers (C10/QS-6); see the ots:secrets:verify /
  # ots:secrets:adopt tasks below.
  MISMATCH_GUIDANCE = <<~MSG
    Likely causes:
      - SECRET was changed/regenerated under existing data (lost .env, rerun of secret generation)
      - the app is pointed at another install's datastore (restored dump, wrong REDIS/VALKEY URL)
    Fix:
      - restore the previous SECRET in .env and restart, or
      - if the rotation was intentional: CONFIRM=yes bundle exec rake ots:secrets:adopt
  MSG

  # Boot enough of the app to reach the datastore. An enforce-mode mismatch
  # raises at boot — for the verifier tasks that IS the finding, so swallow
  # it and let the task report/repair it (Familia is already configured by
  # the time the check runs). Any other boot failure (typically an
  # unreachable datastore) is also swallowed: SecretVerifier.status degrades
  # to :unavailable and the task exits 3 with a message, instead of dying
  # with a raw boot backtrace.
  def self.boot_for_verifier!
    require 'onetime'
    require 'onetime/models'
    Onetime.boot! :cli
  rescue Onetime::SecretVerifierMismatch
    nil
  rescue StandardError => ex
    warn "boot failed (#{ex.class}: #{ex.message}); reporting what can be read without it"
    nil
  end

  def self.write_env(path, existing_lines, updates)
    updated_keys = Set.new
    output       = existing_lines.map do |line|
      stripped = line.strip
      next line if stripped.empty?

      # Check for commented-out derived key placeholders (e.g. #SESSION_SECRET=)
      # but skip block markers (#-----BEGIN/END DERIVED SECRETS-----)
      if stripped.start_with?('#') && !stripped.start_with?('#-')
        commented_content = stripped.sub(/\A#\s*/, '')
        key,              = commented_content.split('=', 2)
        key               = key&.strip
        if key && updates.key?(key)
          updated_keys << key
          next "#{key}=#{updates[key]}"
        end
        next line
      end

      key, = stripped.split('=', 2)
      key  = key&.strip
      if key && updates.key?(key)
        updated_keys << key
        "#{key}=#{updates[key]}"
      else
        line
      end
    end

    (updates.keys - updated_keys.to_a).each do |key|
      output << "#{key}=#{updates[key]}"
    end

    # NOTE: CRLF line endings are normalized to LF here. readlines(chomp: true)
    # strips both \n and \r\n, and we rejoin with "\n". This is intentional —
    # .env files should use LF — but be aware if round-tripping matters.
    File.write(path, output.join("\n") + "\n")
  end
end

namespace :ots do
  namespace :env do
    desc 'Copy .env.example → .env if .env does not exist (idempotent)'
    task :setup do
      env_path = ENV['ENV_FILE'] || File.join(Dir.pwd, '.env')

      if File.exist?(env_path)
        puts "#{env_path} already exists"
      else
        example = env_path.sub(/\.env\z/, '.env.example')
        if File.exist?(example)
          require 'fileutils'
          FileUtils.cp(example, env_path)
          File.chmod(0o600, env_path)
          puts "Copied #{example} → #{env_path} (mode 600)"
        else
          File.write(env_path, "# Generated by rake ots:env:setup\n")
          File.chmod(0o600, env_path)
          puts "Created #{env_path} (mode 600)"
        end
      end
    end
  end

  desc <<~DESC.strip
    Generate SECRET and derive child keys into .env (idempotent).
    Env vars: ENV_FILE=path (default: .env), DERIVE=1 (re-derive child keys only), FORCE=1 (regenerate SECRET)
  DESC
  task secrets: 'ots:env:setup' do
    derive   = %w[1 true].include?(ENV.fetch('DERIVE', nil))
    force    = %w[1 true].include?(ENV.fetch('FORCE', nil))
    env_path = ENV['ENV_FILE'] || File.join(Dir.pwd, '.env')

    existing       = OTSInit.read_env(env_path)
    existing_lines = File.readlines(env_path, chomp: true, encoding: 'UTF-8')

    secret     = existing['SECRET']
    has_secret = secret && !secret.empty? && secret != 'CHANGEME'

    if derive
      abort "ERROR: DERIVE=1 requires SECRET to be set in #{env_path}" unless has_secret
    elsif has_secret && !force
      derive = true
    else
      secret = SecureRandom.hex(64)
    end

    updates           = {}
    updates['SECRET'] = secret unless derive

    # Derived secrets (ADR-008 Category 1): deterministic HKDF from SECRET.
    Onetime::KeyDerivation::PURPOSES.each do |purpose, config|
      next unless config[:env_var] # skip runtime-only purposes (e.g. familia_enc)

      updates[config[:env_var]] = Onetime::KeyDerivation.derive_hex(secret, purpose)
    end

    # Independent secrets (ADR-008 Category 2): random, NOT derived from SECRET.
    OTSInit::INDEPENDENT_SECRETS.each do |env_var|
      if existing[env_var] && !existing[env_var].empty? && existing[env_var] != 'CHANGEME'
        # Keep existing value — do not overwrite
      else
        updates[env_var] = SecureRandom.hex(OTSInit::INDEPENDENT_SECRET_BYTES)
      end
    end

    # Federation secret (ADR-008 Category 3): passphrase, shared across instances.
    federation = existing['FEDERATION_SECRET']
    if federation && !federation.empty? && federation != 'CHANGEME'
      # Keep existing value — do not overwrite
    else
      require 'passforge/wordlist'
      require 'passforge/passphrase'
      updates['FEDERATION_SECRET'] = PassForge::Passphrase.generate(words: 5, separator: '-', capitalize: false)
    end

    OTSInit.write_env(env_path, existing_lines, updates)

    # Verify critical keys were written correctly
    verify = OTSInit.read_env(env_path)
    %w[SECRET SESSION_SECRET IDENTIFIER_SECRET].each do |key|
      val = verify[key]
      if val.nil? || val.empty?
        abort "ERROR: #{key} is empty in #{env_path} after write — file may be malformed"
      end
    end

    # --- Structured output ---
    puts
    puts "Generated #{env_path}"
    puts
    if derive
      puts 'SECRET'
      puts '  (existing, unchanged)'
    else
      puts 'SECRET'
      puts '  64 bytes entropy (128 hex chars)'
    end
    puts

    # Derived secrets summary
    derived_configs = Onetime::KeyDerivation::PURPOSES.select { |_, c| c[:env_var] }
    max_name        = derived_configs.map { |_, c| c[:env_var].length }.max
    puts 'Derived from SECRET (recoverable via HKDF)'
    derived_configs.each do |_purpose, config|
      name = config[:env_var].ljust(max_name)
      puts "  #{name}  info: #{config[:info].ljust(14)} len: #{config[:length]}"
    end
    puts

    # Independent secrets summary
    puts 'Independent (irrecoverable, tied to stored credentials)'
    OTSInit::INDEPENDENT_SECRETS.each do |env_var|
      kept   = existing[env_var] && !existing[env_var].empty? && existing[env_var] != 'CHANGEME'
      suffix = kept ? ' (kept existing)' : ''
      puts "  #{env_var.ljust(max_name)}  #{OTSInit::INDEPENDENT_SECRET_BYTES} bytes#{suffix}"
    end
    fed_kept   = federation && !federation.empty? && federation != 'CHANGEME'
    fed_suffix = fed_kept ? ' (kept existing)' : ''
    puts "  #{'FEDERATION_SECRET'.ljust(max_name)}  5-word passphrase#{fed_suffix}"

    puts
    puts 'Back up this file.'
    puts 'Derived secrets can be regenerated from SECRET.'
    puts 'Independent secrets cannot be recovered if lost.'
  end

  # SECRET lifecycle safety (C10/QS-6): verify/adopt the datastore key
  # verifier that binds the running SECRET to the data it encrypted.
  # See docs/runbooks/secret-rotation.md.
  namespace :secrets do
    desc 'Verify the running SECRET against the datastore key verifier (exit: 0 ok, 1 mismatch, 2 never adopted, 3 unreachable)'
    task :verify do
      OTSInit.boot_for_verifier!

      # Boot itself adopts an absent verifier (CheckSecretVerifier), so
      # "never adopted" is only observable via the boot state, not a
      # post-boot read.
      if Onetime.secret_verifier_state == :adopted
        puts 'not adopted: no key verifier was stored — this run adopted one for the running SECRET'
        exit 2
      end

      case Onetime::SecretVerifier.status
      when :ok
        puts 'ok: SECRET matches the datastore key verifier'
      when :mismatch
        puts 'MISMATCH: the running SECRET is not the one this datastore\'s data was encrypted with.'
        puts OTSInit::MISMATCH_GUIDANCE
        exit 1
      when :unadopted
        puts 'not adopted: no key verifier stored yet (first boot adopts one)'
        exit 2
      when :unavailable
        puts 'unreachable: cannot read the key verifier (is the datastore running?)'
        exit 3
      end
    end

    desc 'Re-stamp the key verifier for the running SECRET after an INTENTIONAL rotation (requires CONFIRM=yes)'
    task :adopt do
      OTSInit.boot_for_verifier!

      status = Onetime::SecretVerifier.status
      case status
      when :ok
        puts 'ok: verifier already matches the running SECRET — nothing to adopt'
        next
      when :unavailable
        abort 'unreachable: cannot reach the datastore — start it and retry'
      end

      # Destructive-adjacent: adopting over a mismatch declares every
      # ciphertext written under the old SECRET expendable (they age out via
      # TTL; reveals fail safe with secret_undecryptable until then).
      if status == :mismatch
        live_secrets = Onetime::Secret.count
        puts 'The stored verifier was written by a DIFFERENT secret.'
        puts "Live secret records in this datastore: #{live_secrets}"
        puts 'Ciphertexts written under the old SECRET will NOT decrypt after adopting;'
        puts 'they are preserved (reveals fail safe) and age out with their TTLs.'
      end

      unless ENV['CONFIRM'] == 'yes'
        abort 'Refusing to adopt without CONFIRM=yes (e.g. CONFIRM=yes bundle exec rake ots:secrets:adopt)'
      end

      Onetime::SecretVerifier.adopt!
      puts 'adopted: key verifier re-stamped for the running SECRET'
      puts 'Restart running app processes so they pick up the new state.'
    end
  end
end
