# apps/web/auth/spec/integration/oauth_idp_protocol_spec.rb
#
# frozen_string_literal: true

# =============================================================================
# TEST TYPE: Integration
# =============================================================================
#
# OAuth2/OIDC IdP protocol conformance — Issue #3104, task 8.
#
# Acts as a hand-rolled OAuth client and drives the IdP endpoints that the
# SP-side `:local` OmniAuth provider talks to in development
# (configure_local_idp_provider in apps/web/auth/config/features/omniauth.rb).
#
# Why direct-drive instead of running through OmniAuth's openid_connect
# strategy: the strategy makes outbound HTTP calls (discovery + /token +
# /userinfo) that don't traverse Rack::Test. Hooking them back to the same
# Rack app via WebMock.to_rack is fragile (boot-time stubbing, no cookies
# across the loopback). The protocol-level invariants the handoff calls
# out — PKCE, `iss` match between discovery and the ID token, code reuse
# rejection — are cleaner to assert against the live booted app directly.
#
# Verifies:
#   - Discovery doc honors the authorization_server_url override
#   - JWKS exposes the RSA public key for OAUTH_JWT_RSA_PRIVATE_KEY
#   - configure_local_idp_provider registered the `:local` provider with the
#     expected options (no HTTP)
#   - /token: PKCE happy path returns access + ID tokens
#   - /token: PKCE verifier mismatch is rejected
#   - /token: same code cannot be exchanged twice
#   - ID token `iss` matches the discovery `issuer` AND verifies with the
#     configured RSA public key
#   - /userinfo: returns claims for a valid bearer access token
#   - /authorize: requires an authenticated account
#
# REQUIREMENTS:
# - Valkey running on port 2121 (pnpm run test:database:start)
# - AUTH_DATABASE_URL set (PostgreSQL or SQLite)
# - AUTHENTICATION_MODE=full
# - AUTH_OAUTH_ENABLED=true (set by spec_helper)
# - OAUTH_JWT_RSA_PRIVATE_KEY (generated by spec_helper if absent)
# - OAUTH_SP_DEV_CLIENT_SECRET (generated by spec_helper if absent)
#
# RUN:
#   source .env.test && pnpm run test:rspec \
#     apps/web/auth/spec/integration/oauth_idp_protocol_spec.rb
#
# Note: lives at integration/ (not integration/full/) on purpose. Path-based
# metadata in spec/spec_helper.rb installs a MockAuthConfig for files under
# /integration/full/ — that mock doesn't expose `oauth_enabled?` and would
# turn the IdP feature off at boot.
# =============================================================================

# Pre-boot setup must run before require_relative '../spec_helper' so the env
# vars are visible to the auth_config the first time Onetime.boot! runs in
# this RSpec process. The boot is one-shot (memoized) — once it happens
# without AUTH_OAUTH_ENABLED, the IdP feature is off for the rest of the
# process and this spec fails or skips.

require 'openssl'
require 'securerandom'

ENV['AUTH_OAUTH_ENABLED']        = 'true'
ENV['OAUTH_ISSUER']              ||= 'http://localhost:3000/auth'
ENV['OAUTH_JWT_RSA_PRIVATE_KEY'] ||= OpenSSL::PKey::RSA.new(2048).to_pem
ENV['OAUTH_SP_DEV_CLIENT_SECRET'] ||= "spec-sp-secret-#{SecureRandom.hex(12)}"

ENV['AUTHENTICATION_MODE'] ||= 'full'
ENV['RACK_ENV']            ||= 'test'

require_relative '../spec_helper'

require 'base64'
require 'cgi'
require 'digest'
require 'json'
require 'jwt'

RSpec.describe 'OAuth/OIDC IdP protocol', type: :integration, sqlite_database: true do
  # Seeded dev SP credentials (see apps/web/auth/initializers/seed_dev_oauth_client.rb).
  # We pin client_id / redirect_uri to the values the seed inserts so the IdP's
  # exact-match validation on /token redirect_uri succeeds.
  let(:client_id)     { 'onetimesecret-sp-dev' }
  let(:client_secret) { ENV.fetch('OAUTH_SP_DEV_CLIENT_SECRET') }
  let(:redirect_uri)  { 'http://localhost:3000/auth/sso/local/callback' }
  let(:issuer)        { ENV.fetch('OAUTH_ISSUER') }

  # PKCE pair — verifier chosen here, S256 challenge derived to match.
  let(:code_verifier) { SecureRandom.urlsafe_base64(64).tr('=', '') }
  let(:code_challenge) do
    Base64.urlsafe_encode64(Digest::SHA256.digest(code_verifier), padding: false)
  end

  before(:all) do
    boot_onetime_app

    # If a prior integration file booted the app before our env vars were set,
    # the OAuth feature won't be configured. Fail loudly rather than skip
    # silently — silent skips hide regressions in CI.
    unless Onetime.auth_config.oauth_enabled?
      raise <<~MSG
        OAuth IdP feature is not enabled in the booted Onetime app. Either:
        - This spec was loaded after another integration spec that booted
          without AUTH_OAUTH_ENABLED, OR
        - SKIP_OAUTH_IDP_TEST_DEFAULTS is set in the environment.
        Run this spec in isolation, or fix spec_helper.rb to set
        AUTH_OAUTH_ENABLED=true before the first boot.
      MSG
    end

    # The dev SP client is seeded by the boot initializer chain. If it's
    # missing (e.g. a prior test truncated oauth_applications), re-seed.
    unless auth_db[:oauth_applications].where(client_id: 'onetimesecret-sp-dev').any?
      require 'auth/initializers/seed_dev_oauth_client'
      Auth::Initializers::SeedDevOAuthClient.new.execute(nil)
    end
  end

  # Tracks rows we insert so we can clean up after each test without taking
  # out unrelated fixtures.
  let(:created_account_ids) { [] }
  let(:created_grant_ids)   { [] }

  after do
    auth_db[:oauth_grants].where(id: created_grant_ids).delete    unless created_grant_ids.empty?
    auth_db[:accounts].where(id: created_account_ids).delete     unless created_account_ids.empty?
  end

  # Inserts a verified account directly. Skipping the rodauth login flow is
  # deliberate: /token doesn't consult a session, it looks the account up via
  # the oauth_grants row's account_id column.
  def create_verified_account
    email = "oauth-test-#{SecureRandom.hex(6)}@example.com"
    id = auth_db[:accounts].insert(
      email: email,
      status_id: 2, # Verified — see migrations/001_initial.rb account_statuses seed
      created_at: Time.now,
      updated_at: Time.now,
    )
    created_account_ids << id
    { id: id, email: email }
  end

  # Inserts an oauth_grant row simulating a successful /authorize response.
  # /token will look up by (oauth_application_id, code) and check the
  # code_challenge against the supplied verifier.
  def seed_authorization_code(account_id:, scopes: 'openid email profile',
                              challenge: code_challenge, method: 'S256',
                              expires_at: Time.now + 300)
    app_id = auth_db[:oauth_applications]
             .where(client_id: client_id)
             .get(:id)
    code = SecureRandom.urlsafe_base64(32)

    grant_id = auth_db[:oauth_grants].insert(
      account_id: account_id,
      oauth_application_id: app_id,
      code: code,
      redirect_uri: redirect_uri,
      expires_in: expires_at,
      scopes: scopes,
      created_at: Time.now,
      code_challenge: challenge,
      code_challenge_method: method,
      access_type: 'online',
    )
    created_grant_ids << grant_id
    { id: grant_id, code: code }
  end

  # HTTP Basic for client_secret_basic auth at /token.
  def basic_auth_header
    'Basic ' + Base64.strict_encode64("#{client_id}:#{client_secret}")
  end

  # Posts an auth code to /token. Wraps the boilerplate of headers + form body.
  # The Accept: application/json header matters because rodauth-oauth's error
  # path falls back to form-post HTML when accepts_json? is false (gem
  # oauth_base.rb:767); JSON-mode SP clients send Accept on /token anyway.
  def post_token(code:, verifier: code_verifier, redirect: redirect_uri)
    header 'Host', 'localhost:3000'
    header 'Authorization', basic_auth_header
    header 'Accept', 'application/json'
    post '/auth/token', {
      grant_type:    'authorization_code',
      code:          code,
      redirect_uri:  redirect,
      code_verifier: verifier,
    }
  end

  # ─── Discovery & JWKS ──────────────────────────────────────────────────────
  describe 'Discovery document' do
    let(:discovery_path) { '/auth/.well-known/openid-configuration' }

    before do
      header 'Host', 'localhost:3000'
      get discovery_path
    end

    it 'returns 200' do
      expect(last_response.status).to eq(200), "Body: #{last_response.body}"
    end

    it 'issuer matches OAUTH_ISSUER override' do
      expect(JSON.parse(last_response.body)['issuer']).to eq(issuer)
    end

    it 'advertises authorize/token/userinfo/jwks endpoints under /auth' do
      body = JSON.parse(last_response.body)
      expect(body['authorization_endpoint']).to end_with('/auth/authorize')
      expect(body['token_endpoint']).to        end_with('/auth/token')
      expect(body['userinfo_endpoint']).to     end_with('/auth/userinfo')
      expect(body['jwks_uri']).to              end_with('/auth/jwks')
    end

    it 'restricts response_types_supported to ["code"]' do
      # The override in features/oauth.rb is the regression net for the
      # implicit/hybrid grant types pulled in transitively by :oidc.
      expect(JSON.parse(last_response.body)['response_types_supported']).to eq(['code'])
    end
  end

  describe 'JWKS' do
    it 'exposes the configured RSA public key' do
      header 'Host', 'localhost:3000'
      get '/auth/jwks'
      expect(last_response.status).to eq(200), "Body: #{last_response.body}"
      keys = JSON.parse(last_response.body)['keys']
      expect(keys).to be_an(Array)
      expect(keys.size).to be >= 1
      key = keys.first
      expect(key['kty']).to eq('RSA')
      expect(key['alg']).to eq('RS256')
      expect(key['kid']).not_to be_empty
      expect(key['n']).not_to be_empty
      expect(key['e']).not_to be_empty
    end
  end

  # ─── SP wiring (no HTTP) ───────────────────────────────────────────────────
  describe 'SP-side wiring (configure_local_idp_provider)' do
    it 'registers the :local provider with the expected options' do
      providers = Auth::Config.instance_variable_get(:@omniauth_providers) || []
      local_entry = providers.find do |entry|
        opts = entry.last
        opts.is_a?(Hash) && opts[:name] == :local
      end

      expect(local_entry).not_to be_nil,
        "Expected :local provider registered. Got providers: #{providers.inspect}"

      strategy_name, opts = local_entry
      expect(strategy_name).to eq(:openid_connect)
      expect(opts[:issuer]).to eq(issuer)
      expect(opts[:pkce]).to be true
      expect(opts[:discovery]).to be true
      expect(opts[:response_type]).to eq(:code)
      expect(opts.dig(:client_options, :identifier)).to eq(client_id)
      expect(opts.dig(:client_options, :redirect_uri)).to eq(redirect_uri)
    end
  end

  # ─── /token PKCE ───────────────────────────────────────────────────────────
  describe '/token PKCE exchange' do
    let(:account) { create_verified_account }

    it 'returns access + id tokens for a valid code + verifier' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token(code: grant[:code])

      expect(last_response.status).to eq(200), "Body: #{last_response.body}"
      body = JSON.parse(last_response.body)
      expect(body['access_token']).to be_a(String).and(satisfy { |s| !s.empty? })
      expect(body['id_token']).to be_a(String).and(satisfy { |s| !s.empty? })
      expect(body['token_type'].to_s.downcase).to eq('bearer')
    end

    it 'rejects a mismatched PKCE verifier' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token(code: grant[:code], verifier: "wrong-#{SecureRandom.hex(16)}")

      expect(last_response.status).to be_between(400, 499)
      body = parse_body_or_location(last_response)
      expect(body['error']).to match(/invalid_(grant|request)/),
        "Expected invalid_grant/invalid_request, got: #{body.inspect}"
    end

    it 'rejects a second exchange of the same code (code reuse)' do
      grant = seed_authorization_code(account_id: account[:id])

      post_token(code: grant[:code])
      expect(last_response.status).to eq(200), "First exchange failed: #{last_response.body}"

      post_token(code: grant[:code])
      expect(last_response.status).to be_between(400, 499)
      body = parse_body_or_location(last_response)
      expect(body['error']).to match(/invalid_(grant|request)/),
        "Expected invalid_grant/invalid_request, got: #{body.inspect}"
    end
  end

  # ─── ID token claims ───────────────────────────────────────────────────────
  describe 'ID token claims' do
    let(:account) { create_verified_account }

    it 'iss matches the discovery issuer and signature verifies with the configured RSA key' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token(code: grant[:code])
      expect(last_response.status).to eq(200), "Body: #{last_response.body}"

      id_token = JSON.parse(last_response.body).fetch('id_token')
      public_key = OpenSSL::PKey::RSA.new(ENV.fetch('OAUTH_JWT_RSA_PRIVATE_KEY')).public_key

      payload, jwt_header = JWT.decode(id_token, public_key, true, algorithm: 'RS256')

      expect(jwt_header['alg']).to eq('RS256')
      expect(payload['iss']).to eq(issuer)
      expect(payload['aud']).to eq(client_id)
      expect(payload['sub']).not_to be_nil
    end

    it 'includes email claim when scope=email is granted' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token(code: grant[:code])

      id_token = JSON.parse(last_response.body).fetch('id_token')
      payload, _h = JWT.decode(id_token, nil, false)

      # `email_verified` and `email` come from get_oidc_param in hooks/oauth.rb.
      expect(payload['email']).to eq(account[:email])
      expect(payload['email_verified']).to eq(true)
    end
  end

  # ─── /userinfo ─────────────────────────────────────────────────────────────
  describe '/userinfo' do
    let(:account) { create_verified_account }

    it 'returns claims for a valid Bearer access token' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token(code: grant[:code])
      expect(last_response.status).to eq(200), "Body: #{last_response.body}"

      access_token = JSON.parse(last_response.body).fetch('access_token')

      header 'Host', 'localhost:3000'
      header 'Authorization', "Bearer #{access_token}"
      get '/auth/userinfo'

      expect(last_response.status).to eq(200), "Body: #{last_response.body}"
      claims = JSON.parse(last_response.body)
      expect(claims['email']).to eq(account[:email])
      expect(claims['sub']).not_to be_nil
    end
  end

  # ─── /authorize gates ──────────────────────────────────────────────────────
  describe '/authorize' do
    it 'requires authentication when no session is present' do
      query = {
        client_id: client_id,
        redirect_uri: redirect_uri,
        response_type: 'code',
        scope: 'openid email',
        state: 'teststate',
        code_challenge: code_challenge,
        code_challenge_method: 'S256',
      }.map { |k, v| "#{k}=#{CGI.escape(v.to_s)}" }.join('&')

      header 'Host', 'localhost:3000'
      get "/auth/authorize?#{query}"

      # require_account redirects unauthenticated users to login (302) or
      # responds 401 in JSON-mode contexts. Should not directly 200 with an
      # authorization page.
      expect([302, 401]).to include(last_response.status),
        "Expected redirect or 401, got #{last_response.status}: #{last_response.body[0, 200]}"
    end
  end

  # Parses a 4xx/redirect response body looking for OAuth `error` field.
  # The gem can either render a JSON error or redirect with ?error=... in
  # the Location header; this helper normalizes both shapes for assertions.
  def parse_body_or_location(response)
    return JSON.parse(response.body) if response.body.start_with?('{') rescue nil

    if response.headers['Location']
      query = URI.parse(response.headers['Location']).query.to_s
      Hash[query.split('&').map { |kv| kv.split('=', 2) }]
    else
      { 'error' => 'unknown', 'raw' => response.body[0, 200] }
    end
  end
end
