# apps/web/auth/spec/integration/oauth/oauth_idp_endpoints_spec.rb
#
# frozen_string_literal: true

# =============================================================================
# TEST TYPE: Integration
# =============================================================================
#
# OAuth2/OIDC IdP — endpoint-level error and input validation. Issue #3104, task 9.
#
# Complements oauth_idp_protocol_spec.rb. That file proves the SP→IdP loop
# works end-to-end (the protocol view). This file zooms in on each endpoint's
# error responses, parameter validation, and authorization handling — the
# kinds of things an external SP misconfiguration would surface.
#
# Out of scope here:
#   - The cross-endpoint authorization-code flow (covered by protocol_spec)
#   - /authorize parameter validation behind the require_account gate
#     (the gem redirects to login *before* validating params, so reaching
#     those code paths needs a logged-in rodauth session — significantly
#     more setup than the rest of this file). Tracked separately in #3104
#     follow-up.
#
# REQUIREMENTS:
# - Valkey on port 2121 (pnpm run test:database:start)
# - AUTHENTICATION_MODE=full
# - AUTH_OAUTH_ENABLED=true (set by spec_helper)
# - OAUTH_JWT_RSA_PRIVATE_KEY (generated by spec_helper if absent)
# - OAUTH_SP_DEV_CLIENT_SECRET (generated by spec_helper if absent)
#
# RUN:
#   source .env.test && \
#     bundle exec rspec apps/web/auth/spec/integration/oauth/oauth_idp_endpoints_spec.rb
#
# This spec lives at integration/oauth/ (not integration/full/) for the same
# reason protocol_spec does: the path-keyed MockAuthConfig matching /integration/full/
# doesn't expose oauth_enabled? and would turn the IdP feature off at boot.
# integration/oauth/ dodges that regex; the dedicated spec:integration:oauth
# rake task runs it under full mode.
# =============================================================================

require 'openssl'
require 'securerandom'

# Pre-boot env: same shape as protocol_spec so the two can run in the same
# rspec invocation (boot is memoized; first writer wins on AUTH_OAUTH_ENABLED).
ENV['AUTH_OAUTH_ENABLED']        = 'true'
ENV['OAUTH_ISSUER']              ||= 'http://localhost:3000/auth'
ENV['OAUTH_JWT_RSA_PRIVATE_KEY'] ||= OpenSSL::PKey::RSA.new(2048).to_pem
ENV['OAUTH_SP_DEV_CLIENT_SECRET'] ||= "spec-sp-secret-#{SecureRandom.hex(12)}"

ENV['AUTHENTICATION_MODE'] ||= 'full'
ENV['RACK_ENV']            ||= 'test'

require_relative '../../spec_helper'

require 'base64'
require 'cgi'
require 'digest'
require 'json'
require 'jwt'

RSpec.describe 'OAuth/OIDC IdP endpoints', type: :integration, sqlite_database: true do
  let(:client_id)     { 'onetimesecret-sp-dev' }
  let(:client_secret) { ENV.fetch('OAUTH_SP_DEV_CLIENT_SECRET') }
  let(:redirect_uri)  { 'http://localhost:3000/auth/sso/local/callback' }
  let(:issuer)        { ENV.fetch('OAUTH_ISSUER') }

  let(:code_verifier) { SecureRandom.urlsafe_base64(64).tr('=', '') }
  let(:code_challenge) do
    Base64.urlsafe_encode64(Digest::SHA256.digest(code_verifier), padding: false)
  end

  before(:all) do
    boot_onetime_app

    unless Onetime.auth_config.oauth_enabled?
      raise <<~MSG
        OAuth IdP feature is not enabled in the booted Onetime app. Run this
        spec in isolation or before any other integration spec that boots
        without AUTH_OAUTH_ENABLED.
      MSG
    end

    # Re-seed the dev SP client if a prior test truncated it.
    unless auth_db[:oauth_applications].where(client_id: 'onetimesecret-sp-dev').any?
      require 'auth/initializers/seed_dev_oauth_client'
      Auth::Initializers::SeedDevOAuthClient.new.execute(nil)
    end
  end

  let(:created_account_ids) { [] }
  let(:created_grant_ids)   { [] }

  after do
    auth_db[:oauth_grants].where(id: created_grant_ids).delete    unless created_grant_ids.empty?
    auth_db[:accounts].where(id: created_account_ids).delete     unless created_account_ids.empty?
  end

  # ─── Helpers (kept small; mostly duplicated from protocol_spec to keep the
  #     two files independently runnable without a shared example_group file).

  def create_verified_account
    email = "oauth-ep-#{SecureRandom.hex(6)}@example.com"
    id = auth_db[:accounts].insert(
      email: email,
      status_id: 2,
      created_at: Time.now,
      updated_at: Time.now,
    )
    created_account_ids << id
    { id: id, email: email }
  end

  def seed_authorization_code(account_id:, scopes: 'openid email profile',
                              challenge: code_challenge, method: 'S256',
                              expires_at: Time.now + 300)
    app_id = auth_db[:oauth_applications].where(client_id: client_id).get(:id)
    code = SecureRandom.urlsafe_base64(32)

    grant_id = auth_db[:oauth_grants].insert(
      account_id: account_id,
      oauth_application_id: app_id,
      code: code,
      redirect_uri: redirect_uri,
      expires_in: expires_at,
      scopes: scopes,
      created_at: Time.now,
      code_challenge: challenge,
      code_challenge_method: method,
      access_type: 'online',
    )
    created_grant_ids << grant_id
    { id: grant_id, code: code }
  end

  def basic_auth_header(id: client_id, secret: client_secret)
    'Basic ' + Base64.strict_encode64("#{id}:#{secret}")
  end

  def post_token(form, authorization: basic_auth_header)
    header 'Host', 'localhost:3000'
    header 'Authorization', authorization if authorization
    header 'Accept', 'application/json'
    post '/auth/token', form
  end

  # Parses a 4xx body that may be JSON or a redirect with ?error=... in
  # the Location header.
  def parse_error(response)
    body = response.body.to_s
    return JSON.parse(body) if body.start_with?('{')

    if response.headers['Location']
      query = URI.parse(response.headers['Location']).query.to_s
      Hash[query.split('&').map { |kv| kv.split('=', 2).then { |k, v| [k, CGI.unescape(v.to_s)] } }]
    else
      { 'error' => 'unknown', 'raw' => body[0, 200] }
    end
  end

  # ─── Discovery (extended metadata) ───────────────────────────────────────
  describe 'GET /.well-known/openid-configuration extended metadata' do
    let(:body) do
      header 'Host', 'localhost:3000'
      get '/auth/.well-known/openid-configuration'
      JSON.parse(last_response.body)
    end

    it 'advertises only authorization_code and refresh_token grant types' do
      expect(body['grant_types_supported']).to match_array(%w[authorization_code refresh_token])
    end

    it 'advertises S256 via the oauth-authorization-server metadata endpoint' do
      # oidc.rb#openid_configuration_body filters response keys through
      # VALID_METADATA_KEYS, which excludes code_challenge_methods_supported.
      # The OAuth 2.0 metadata endpoint (RFC 8414) keeps it.
      header 'Host', 'localhost:3000'
      get '/auth/.well-known/oauth-authorization-server'
      oauth_meta = JSON.parse(last_response.body)

      # The gem assigns a single value, not an array — assert via String#include?
      # which works whether the value is a String or an Array.
      expect(oauth_meta['code_challenge_methods_supported']).to include('S256')
    end

    it 'advertises RS256 in id_token_signing_alg_values_supported' do
      expect(body['id_token_signing_alg_values_supported']).to include('RS256')
    end

    it 'advertises openid, email, profile, and offline_access in scopes_supported' do
      # offline_access must be advertised here (it derives from
      # oauth_application_scopes): without it the /authorize scope intersection
      # strips offline_access before the grant is written, so the :oidc layer
      # never issues a refresh token. This is the discovery-level regression
      # guard for the server allow-list; the seeded SP's per-application scopes
      # column is covered by seed_dev_oauth_client_idempotency_spec.
      expect(body['scopes_supported']).to include('openid', 'email', 'profile', 'offline_access')
    end

    it 'advertises token_endpoint_auth_methods_supported' do
      methods = body['token_endpoint_auth_methods_supported']
      expect(methods).to be_an(Array)
      expect(methods).to include('client_secret_basic').or include('client_secret_post')
    end

    it 'advertises subject_types_supported' do
      expect(body['subject_types_supported']).to be_an(Array)
      expect(body['subject_types_supported']).not_to be_empty
    end
  end

  # ─── JWKS shape ──────────────────────────────────────────────────────────
  describe 'GET /auth/jwks key metadata' do
    let(:key) do
      header 'Host', 'localhost:3000'
      get '/auth/jwks'
      JSON.parse(last_response.body)['keys'].first
    end

    it 'marks the key as use=sig' do
      expect(key['use']).to eq('sig')
    end
  end

  # ─── /token authentication ───────────────────────────────────────────────
  describe 'POST /auth/token client authentication' do
    let(:account) { create_verified_account }

    it 'returns 401 invalid_client when client_id is unknown' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token(
        { grant_type: 'authorization_code', code: grant[:code],
          redirect_uri: redirect_uri, code_verifier: code_verifier },
        authorization: basic_auth_header(id: 'no-such-client'),
      )

      expect(last_response.status).to eq(401), "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to eq('invalid_client')
    end

    it 'returns 401 invalid_client when client_secret is wrong' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token(
        { grant_type: 'authorization_code', code: grant[:code],
          redirect_uri: redirect_uri, code_verifier: code_verifier },
        authorization: basic_auth_header(secret: 'wrong-secret'),
      )

      expect(last_response.status).to eq(401), "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to eq('invalid_client')
    end

    it 'returns 401 invalid_client when no Authorization header is provided' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token(
        { grant_type: 'authorization_code', code: grant[:code],
          redirect_uri: redirect_uri, code_verifier: code_verifier },
        authorization: nil,
      )

      expect(last_response.status).to eq(401), "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to eq('invalid_client')
    end

    it 'sets WWW-Authenticate on the 401 response' do
      post_token(
        { grant_type: 'authorization_code', code: 'irrelevant',
          redirect_uri: redirect_uri, code_verifier: code_verifier },
        authorization: nil,
      )

      expect(last_response.status).to eq(401)
      expect(last_response.headers['WWW-Authenticate']).to be_a(String).and(satisfy { |v| !v.empty? })
    end
  end

  # ─── /token request validation ───────────────────────────────────────────
  describe 'POST /auth/token grant validation' do
    let(:account) { create_verified_account }

    it 'rejects an unknown grant_type' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token({ grant_type: 'password',
                   code: grant[:code],
                   redirect_uri: redirect_uri,
                   code_verifier: code_verifier })

      expect(last_response.status).to be_between(400, 499),
        "Body: #{last_response.body}"
      err = parse_error(last_response)['error']
      expect(err).to match(/invalid_request|unsupported_grant_type/),
        "Got error: #{err.inspect}"
    end

    it 'rejects a missing grant_type' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token({ code: grant[:code],
                   redirect_uri: redirect_uri,
                   code_verifier: code_verifier })

      expect(last_response.status).to be_between(400, 499),
        "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to match(/invalid_request/)
    end

    it 'rejects an authorization_code grant with no code' do
      post_token({ grant_type: 'authorization_code',
                   redirect_uri: redirect_uri,
                   code_verifier: code_verifier })

      expect(last_response.status).to be_between(400, 499),
        "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to match(/invalid_request|invalid_grant/)
    end

    it 'rejects a mismatched redirect_uri at /token' do
      grant = seed_authorization_code(account_id: account[:id])
      post_token({ grant_type: 'authorization_code',
                   code: grant[:code],
                   redirect_uri: 'http://attacker.example.com/callback',
                   code_verifier: code_verifier })

      expect(last_response.status).to be_between(400, 499),
        "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to match(/invalid_grant|invalid_request/)
    end

    it 'rejects an unknown authorization code' do
      post_token({ grant_type: 'authorization_code',
                   code: "no-such-code-#{SecureRandom.hex(8)}",
                   redirect_uri: redirect_uri,
                   code_verifier: code_verifier })

      expect(last_response.status).to be_between(400, 499),
        "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to match(/invalid_grant|invalid_request/)
    end

    it 'rejects refresh_token grant with no refresh_token' do
      post_token({ grant_type: 'refresh_token' })

      expect(last_response.status).to be_between(400, 499),
        "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to match(/invalid_request/)
    end
  end

  # ─── /userinfo authorization ─────────────────────────────────────────────
  describe 'GET /auth/userinfo authorization' do
    it 'returns 401 invalid_token with no Authorization header' do
      header 'Host', 'localhost:3000'
      get '/auth/userinfo'

      expect(last_response.status).to eq(401), "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to eq('invalid_token')
    end

    it 'returns 401 invalid_token with a malformed Authorization header' do
      header 'Host', 'localhost:3000'
      header 'Authorization', 'NotBearer something'
      get '/auth/userinfo'

      expect(last_response.status).to eq(401), "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to eq('invalid_token')
    end

    it 'returns 401 invalid_token with an unknown bearer token' do
      header 'Host', 'localhost:3000'
      header 'Authorization', "Bearer not-a-real-token-#{SecureRandom.hex(16)}"
      get '/auth/userinfo'

      expect(last_response.status).to eq(401), "Body: #{last_response.body}"
      expect(parse_error(last_response)['error']).to eq('invalid_token')
    end

    it 'sets WWW-Authenticate on the 401 response' do
      header 'Host', 'localhost:3000'
      get '/auth/userinfo'

      expect(last_response.status).to eq(401)
      expect(last_response.headers['WWW-Authenticate']).to be_a(String).and(satisfy { |v| !v.empty? })
    end
  end
end
