# try/unit/models/organization_familia_v2_try.rb
#
# frozen_string_literal: true

#
# Familia v2 relationship validation tests for Organization model
# Tests verify that auto-generated methods from participates_in work correctly
#
# CRITICAL: Organization should NOT manually define sorted_set :members or sorted_set :teams
# Instead, these are AUTO-GENERATED:
# - members: by Customer.participates_in Organization, :members
# - teams: by Team.participates_in Organization, :teams
#
# Auto-generated methods tested:
# - org.members (sorted_set) - auto-created by Customer participation
# - org.teams (sorted_set) - auto-created by Team participation
# - org.add_members_instance(customer) - auto-created
# - org.remove_members_instance(customer) - auto-created
# - customer.organization_instances - reverse lookup
# - customer.organization_ids - efficient ID-only access
# - customer.organization? - membership check
# - customer.organization_count - count without loading

require_relative '../../support/test_models'

begin
  OT.boot! :test, false
rescue Redis::CannotConnectError, Redis::ConnectionError => e
  puts "SKIP: Requires Redis connection (#{e.class})"
  exit 0
end

# Setup
@owner = Onetime::Customer.create!(email: "org_owner_#{Familia.now.to_i}@test.com")
@member = Onetime::Customer.create!(email: "org_member_#{Familia.now.to_i}@test.com")

## Creating organization
@org = Onetime::Organization.create!("Acme Corp", @owner, "billing@acme.com")
[@org.class, @org.display_name, @org.owner_id]
#=> [Onetime::Organization, "Acme Corp", @owner.custid]

## Owner automatically added as member
@org.member?(@owner)
#=> true

## Members collection auto-generated
@org.members.class
#=> Familia::SortedSet

## Members collection contains owner objid
@org.members.member?(@owner.objid)
#=> true

## Owner helpers
[@org.owner.custid, @org.owner?(@owner), @org.can_modify?(@owner)]
#=> [@owner.custid, true, true]

## Non-owner cannot modify
@org.can_modify?(@member)
#=> false

## Adding members
@org.add_member(@member)
@org.member?(@member)
#=> true

## Members collection updated
@org.members.size
#=> 2

## Reverse relationship method exists (customer -> organizations)
@owner.respond_to?(:organization_instances)
#=> true

## Participations are tracked in Redis
@owner.participations.to_a.any? { |p| p.include?(@org.orgid) }
#=> true

## Member participations tracked after adding
@member.participations.to_a.any? { |p| p.include?(@org.orgid) }
#=> true

## List members with bulk loading
@members = @org.list_members
@members.size
#=> 2

## All members are Customer instances
@members.all? { |m| m.is_a?(Onetime::Customer) }
#=> true

## Members include owner and member
@members.map(&:custid).sort
#=> [@owner.custid, @member.custid].sort

## Removing members cleans forward side
@org.remove_member(@member)
@org.member?(@member)
#=> false

## Participations updated after removal
@member.participations.to_a.any? { |p| p.include?(@org.orgid) }
#=> false

## Count decremented
@org.member_count
#=> 1

## Customer add_to_organization_members method works
@member.add_to_organization_members(@org, Familia.now.to_f)
@org.member?(@member)
#=> true

## Customer remove_from_organization_members method works
@member.remove_from_organization_members(@org)
@org.member?(@member)
#=> false

## Team-Organization relationship (if team created with org_id)
@team = Onetime::Team.create!("Engineering", @owner, @org.orgid)
@team.org_id
#=> @org.orgid

## Organization has teams collection (auto-generated by Team.participates_in)
@org.teams.class
#=> Familia::SortedSet

## Organization teams collection contains team objid
@org.teams.member?(@team.objid)
#=> true

## Team participations tracked
@team.participations.to_a.any? { |p| p.include?(@org.orgid) }
#=> true

## Organization can list teams
@org.teams.size
#=> 1

# Teardown
@team.destroy!
@org.destroy!
@owner.destroy!
@member.destroy!
