# try/unit/models/team_familia_v2_try.rb
#
# Familia v2 relationship validation tests for Team model
# Tests verify that auto-generated methods from participates_in work correctly
#
# CRITICAL: Team should NOT manually define sorted_set :members
# Instead, members is AUTO-GENERATED by Customer.participates_in Team, :members
#
# Auto-generated methods tested:
# - team.members (sorted_set) - auto-created by Customer participation
# - team.add_members_instance(customer) - auto-created
# - team.remove_members_instance(customer) - auto-created
# - customer.team_instances - reverse lookup
# - customer.team_ids - efficient ID-only access
# - customer.team? - membership check
# - customer.team_count - count without loading

require_relative '../../support/test_models'

begin
  OT.boot! :test, false
rescue Redis::CannotConnectError, Redis::ConnectionError => e
  puts "SKIP: Requires Redis connection (#{e.class})"
  exit 0
end

# Setup test data
@owner = Onetime::Customer.create!(email: "team_owner_#{Familia.now.to_i}@test.com")
@member = Onetime::Customer.create!(email: "team_member_#{Familia.now.to_i}@test.com")

## Creating a team adds owner as first member
@team = Onetime::Team.create!("Engineering", @owner)
[@team.class, @team.owner_id]
#=> [Onetime::Team, @owner.custid]

## Owner is automatically added as member via Familia v2
@team.member?(@owner)
#=> true

## Members collection is auto-generated sorted_set
@team.members.class
#=> Familia::SortedSet

## Members collection contains owner objid
@team.members.member?(@owner.objid)
#=> true

## Adding members uses auto-generated method
@team.add_member(@member)
@team.member?(@member)
#=> true

## Members collection updated after add
@team.members.size
#=> 2

## Reverse relationship method exists (customer -> teams)
@owner.respond_to?(:team_instances)
#=> true

## Participations are tracked in Redis
@owner.participations.to_a.any? { |p| p.include?(@team.teamid) }
#=> true

## Member participations tracked
@member.participations.to_a.any? { |p| p.include?(@team.teamid) }
#=> true

## Bulk loading members with load_multi
@members = @team.list_members
@members.size
#=> 2

## All members are Customer instances
@members.all? { |m| m.is_a?(Onetime::Customer) }
#=> true

## Members include both owner and member
@members.map(&:custid).sort
#=> [@owner.custid, @member.custid].sort

## Removing members cleans forward side
@team.remove_member(@member)
@team.member?(@member)
#=> false

## Participations updated after removal
@member.participations.to_a.any? { |p| p.include?(@team.teamid) }
#=> false

## Count decremented after removal
@team.member_count
#=> 1

## Customer add_to_team_members method works
@member.add_to_team_members(@team, Familia.now.to_f)
@team.member?(@member)
#=> true

## Customer remove_from_team_members method works
@member.remove_from_team_members(@team)
@team.member?(@member)
#=> false

# Teardown
@team.destroy!
@owner.destroy!
@member.destroy!
