##
# This is the RuboCop configuration file.
# It contains the rules and settings for the RuboCop linter.
#
# Enable/disable the cops individually. For more information,
# refer to the RuboCop documentation:
# https://docs.rubocop.org/rubocop/cops.html
#
# Running `rubocop --regenerate-todo` will update the todo file
# with the latest state of the onion (using the same options
# as those documented at the top of the todo file). This is
# useful for a gradual migration of the codebase.
#
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  UseCache: true
  MaxFilesInCache: 100
  TargetRubyVersion: 3.0
  Exclude:
    - 'migrate/**/*.rb'
    - 'migrate/*.rb'
    - 'try/**/*'
    - 'try/*.rb'
    - 'vendor/**/*'

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/ClassLength:
  Enabled: true
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 40
  CountAsOne: ['method_call']

Metrics/ModuleLength:
  Enabled: true
  Max: 250
  CountAsOne: ['method_call']

Performance/Size:
  Enabled: true
  Exclude:
  #   - lib/example.rb

Style/NegatedIfElseCondition:
  Enabled: true
