#!/usr/bin/env bash

# install-test.sh
#
# Switches this checkout to test mode:
#   - Generates .envrc if missing
#   - Verifies .env.test exists (symlinked from OTS_DEV_CONFIG or present)
#   - Starts the test Valkey instance on port 2121 (no persistence)
#   - Creates .test-mode marker so .envrc loads .env.test via direnv
#   - Smoke-tests that config resolves to the test database
#
# To switch back to dev mode, run install-dev.sh (removes .test-mode).
#
# Idempotent: safe to re-run at any time.

set -euo pipefail

# Sanity check
if [[ ! -f "Gemfile" ]]; then
    echo "Error: Run this from an OTS checkout root"
    exit 1
fi

missing_required=()
command -v direnv &>/dev/null || missing_required+=("direnv  (Directory environments):  https://direnv.net/docs/installation.html")
command -v pnpm   &>/dev/null || missing_required+=("pnpm    (Node package manager):  https://pnpm.io/installation")
command -v "${VALKEY_CLI:-valkey-cli}" &>/dev/null || missing_required+=("valkey-cli (Valkey CLI client):  https://valkey.io/download/")
if (( ${#missing_required[@]} > 0 )); then
    echo "Error: Required tools missing:"
    for tool in "${missing_required[@]}"; do
        echo "  - $tool"
    done
    exit 1
fi

# --- .envrc ---------------------------------------------------------

if [[ ! -f ".envrc" ]]; then
    echo "Creating .envrc..."
    cat > ".envrc" << 'ENVRC'
# .envrc — generated by install-test.sh
#
# direnv loads this automatically when you cd into the checkout.
# Mode is controlled by the .test-mode file:
#   install-test.sh  creates it  → test mode
#   install-dev.sh   removes it  → dev mode

source_up_if_exists

watch_file .test-mode

if [ -f .test-mode ]; then
  export OTS_ENV_LOADED=test
  dotenv_if_exists .env.test
else
  export OTS_ENV_LOADED=dev
  dotenv_if_exists

  # .env.local overrides happen last if the file exists. And only in dev mode.
  #
  # Because each dotenv call just exports variables into the same sub-shell, the order
  # you write them determines precedence — later calls override earlier ones. So
  # .env.local values would win over .env values in the above setup.
  #
  test -f .env.local && dotenv .env.local
fi
ENVRC
    echo "Created: .envrc"
else
    echo "OK:   .envrc already exists"
fi

# --- .env.test -------------------------------------------------------

OTS_DEV_CONFIG="${OTS_DEV_CONFIG:-$HOME/.config/onetimesecret-dev}"

if [[ -f ".env.test" ]]; then
    echo "OK:   .env.test exists"
elif [[ -f "$OTS_DEV_CONFIG/.env.test" ]]; then
    ln -snf "$OTS_DEV_CONFIG/.env.test" .env.test
    echo "Link: .env.test -> $OTS_DEV_CONFIG/.env.test"
else
    echo "Error: .env.test not found"
    echo "  Expected at: $OTS_DEV_CONFIG/.env.test (or a local file)"
    exit 1
fi

# Verify .env.test sets RACK_ENV=test
if ! grep -q '^RACK_ENV=test' .env.test; then
    echo "Warning: .env.test does not set RACK_ENV=test"
    echo "  Tests rely on RACK_ENV=test to load spec/*.test.yaml configs"
fi

# --- PostgreSQL test database -----------------------------------------

pg_superuser_url="${AUTH_DATABASE_URL_TEST_SUPERUSER:-}"
if [[ -z "$pg_superuser_url" ]]; then
    # Fall back to .env.test if direnv hasn't loaded yet
    pg_superuser_url=$(grep '^AUTH_DATABASE_URL_TEST_SUPERUSER=' .env.test 2>/dev/null | cut -d= -f2- || true)
fi

if [[ -n "$pg_superuser_url" ]] && command -v psql &>/dev/null; then
    echo "Provisioning PostgreSQL test database..."

    # Extract connection parts from the superuser URL.
    # Parse: postgresql://user[:pass]@host[:port]/dbname
    pg_db=$(echo "$pg_superuser_url" | sed -E 's|.*://[^/]*/||')

    # Create the database if it doesn't exist (createdb is idempotent-ish)
    if psql "$pg_superuser_url" -c "SELECT 1" &>/dev/null; then
        echo "OK:   Database '$pg_db' exists"
    else
        # Connect to 'postgres' maintenance DB to create the test DB
        pg_maintenance_url=$(echo "$pg_superuser_url" | sed -E "s|/[^/]*$|/postgres|")
        createdb_output=$(psql "$pg_maintenance_url" -c "CREATE DATABASE \"$pg_db\"" 2>&1) || {
            if echo "$createdb_output" | grep -q "already exists"; then
                echo "OK:   Database '$pg_db' already exists"
            else
                echo "Error: Failed to create database '$pg_db': $createdb_output"
                exit 1
            fi
        }
        echo "OK:   Created database '$pg_db'"
    fi

    # Run the shared provisioning script (roles, grants, schema reset)
    psql "$pg_superuser_url" -f apps/web/auth/migrations/schemas/postgres/initialize_test_db.sql -v ON_ERROR_STOP=1
    echo "OK:   PostgreSQL roles and grants provisioned"
else
    if [[ -n "$pg_superuser_url" ]]; then
        echo "Skip: psql not found — skipping PostgreSQL setup"
    else
        echo "Skip: AUTH_DATABASE_URL_TEST_SUPERUSER not set — skipping PostgreSQL setup"
    fi
fi

# --- Generated locales ------------------------------------------------

echo "---"
echo "Generating merged locale files..."
if command -v python3 &>/dev/null; then
    python3 locales/scripts/build/compile.py --all --merged
    echo "OK:   Locales generated in generated/locales/"
else
    echo "Skip: python3 not found — skipping locale generation"
fi

# --- Test Valkey on port 2121 ----------------------------------------

valkey_cli="${VALKEY_CLI:-valkey-cli}"

echo "---"
echo "Starting test Valkey on port 2121..."

if $valkey_cli -p 2121 ping &>/dev/null; then
    echo "OK:   Test Valkey already running on port 2121"
else
    pnpm run test:database:start

    started=false
    for _i in 1 2 3 4 5 6 7 8 9 10; do
        if $valkey_cli -p 2121 ping &>/dev/null; then
            started=true
            break
        fi
        sleep 0.5
    done

    if $started; then
        echo "OK:   Test Valkey started on port 2121"
    else
        echo "Error: Test Valkey did not start on port 2121"
        echo "  Try manually: pnpm run test:database:start:fg"
        exit 1
    fi
fi

# --- Activate test mode ----------------------------------------------

echo "---"
echo "Activating test mode..."
touch .test-mode
direnv allow .

# --- Smoke test ------------------------------------------------------

echo "---"
echo "Verifying test environment config..."

test_uri=$(direnv exec . ruby -e '
  ENV["RACK_ENV"] = "test"
  require_relative "lib/onetime"
  OT::Config.before_load
  raw  = OT::Config.load
  conf = OT::Config.after_load(raw)
  puts conf.dig("redis", "uri")
' || true)

if [[ "$test_uri" == *":2121"* ]]; then
    echo "OK:   Config resolves to test database ($test_uri)"
else
    echo "Warning: Config did not resolve to port 2121 (got: ${test_uri:-<empty>})"
    echo "  spec/config.test.yaml should hardcode redis://127.0.0.1:2121/0"
    echo "  Verify RACK_ENV=test is set and ConfigResolver finds the test config"
fi

# --- Done ------------------------------------------------------------

echo "---"
echo "Test environment ready. To switch back to dev mode: install-dev.sh"
