// scripts/globes/build.mjs
//
// Render every icon in presets.mjs and write OtsSprites.vue.
//
//   node build.mjs              all icons
//   node build.mjs earth-japan  just the named icon(s); the sprite is only written for a full build
//   node build.mjs --check      exit 1 if the committed OtsSprites.vue is not what the presets
//                               produce (the pipeline is pure JS, so output is deterministic)
//
// Standalone SVGs for each icon are also written to out/ for previewing.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import presets from './presets.mjs';
import { makeGlobe, standaloneSvg } from './make-globe.mjs';

const check = process.argv.includes('--check');
const only = process.argv.slice(2).filter((a) => a !== '--check');
const names = only.length ? only : Object.keys(presets);
mkdirSync(new URL('./out/', import.meta.url), { recursive: true });

const symbols = [];
for (const name of names) {
  if (!presets[name]) throw new Error(`no preset named ${name}`);
  const paths = makeGlobe(presets[name]);
  writeFileSync(new URL(`./out/ots-${name}.svg`, import.meta.url), standaloneSvg(paths));

  // One attribute per line, as the repo's vue/max-attributes-per-line rule wants.
  const els = paths.map((p) => {
    const attrs = [...p.matchAll(/([a-z-]+)="([^"]*)"/g)].map(([, k, v]) => `          ${k}="${v}"`);
    return `        <path\n${attrs.join('\n')} />`;
  });
  symbols.push(`      <symbol\n        viewBox="0 0 512 512"\n        id="ots-${name}">\n${els.join('\n')}\n      </symbol>`);
  console.log(`ots-${name}`);
}

if (!only.length) {
  const vue = `<!-- src/shared/components/icons/sprites/OtsSprites.vue -->

<!--
Custom Onetime Secret icons. GENERATED by scripts/globes/build.mjs from
scripts/globes/presets.mjs; edit the presets and rebuild rather than editing
the paths here:

  cd scripts/globes && npm install && npm run build

Regional globes drawn to match fa6-solid-earth-* (512 viewBox, r=256 disc,
land cut out inside an r=208 rim), from Natural Earth 1:50m data (public
domain). The focus country or region is cut out at full contrast; other land
is filled with currentColor at 50% opacity, which keeps it distinct from both
the ocean and the focus in light and dark themes.

Usage:
    <OIcon collection="ots" name="earth-canada" />
    <svg><use href="#ots-earth-canada"></use></svg>
-->
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
${symbols.join('\n')}
    </defs>
  </svg>
</template>
`;
  const target = new URL('../../src/shared/components/icons/sprites/OtsSprites.vue', import.meta.url);
  if (check) {
    if (readFileSync(target, 'utf8') !== vue) {
      console.error('OtsSprites.vue is out of date with presets.mjs; run `npm run build`');
      process.exit(1);
    }
    console.log('OtsSprites.vue is up to date');
  } else {
    writeFileSync(target, vue);
    console.log('wrote src/shared/components/icons/sprites/OtsSprites.vue');
  }
}
