# lib/onetime/cli/completion_command.rb
#
# frozen_string_literal: true

#
# Emits a shell completion script for `ots`.
#
# The command tree is dynamically discovered (billing/app commands are
# auto-required), so completion is generated by walking the live Dry::CLI
# registry rather than hand-maintaining a list. The output is a STATIC script
# with the full command tree baked in — the completer never shells out to
# `ots`, so Tab is instant and never boots the app.
#
# Regenerate on demand:
#   ots completion bash > /etc/bash_completion.d/ots
#
# In the OCI image this is baked at build time; see the Dockerfile.
#
# Usage:
#   ots completion bash
#

module Onetime
  module CLI
    class CompletionCommand < DelayBootCommand
      desc 'Generate a shell completion script (bash)'

      argument :shell,
        required: false,
        default: 'bash',
        values: %w[bash],
        desc: 'Target shell'

      def call(shell: 'bash', **)
        case shell
        when 'bash'
          puts bash_script
        else
          warn "Unsupported shell: #{shell} (supported: bash)"
          exit 1
        end
      end

      private

      # Newline-separated list of every non-hidden command path, e.g.
      #   "billing"
      #   "billing catalog drift"
      def command_paths
        registry = Onetime::CLI.instance_variable_get(:@commands)
        root     = registry.instance_variable_get(:@root)
        out      = []
        walk(root, [], out)
        out.sort.uniq
      end

      def walk(node, prefix, out)
        (node.instance_variable_get(:@children) || {}).each do |name, child|
          path = prefix + [name]
          out << path.join(' ') unless child.instance_variable_get(:@hidden)
          walk(child, path, out)
        end
      end

      def bash_script
        commands = command_paths.join("\n")
        <<~BASH
          # bash completion for `ots` — generated by `ots completion bash`.
          # Static command tree; the completer never invokes ots, so Tab is instant.
          _ots_commands='#{commands}'

          _ots_complete() {
            local cur cword words i w path prefix line rest candidates
            cur="${COMP_WORDS[COMP_CWORD]}"
            words=("${COMP_WORDS[@]}")
            cword=$COMP_CWORD

            # Rebuild the subcommand path typed so far, skipping the program
            # name and any flags/arguments starting with '-'.
            path=()
            for ((i = 1; i < cword; i++)); do
              w="${words[i]}"
              [[ "$w" == -* ]] && continue
              path+=("$w")
            done
            prefix="${path[*]}"

            candidates=()
            while IFS= read -r line; do
              [[ -z "$line" ]] && continue
              if [[ -z "$prefix" ]]; then
                candidates+=("${line%% *}")
              elif [[ "$line" == "$prefix "* ]]; then
                rest="${line#"$prefix" }"
                candidates+=("${rest%% *}")
              fi
            done <<< "$_ots_commands"

            COMPREPLY=($(compgen -W "$(printf '%s\\n' "${candidates[@]}" | sort -u)" -- "$cur"))
          }

          complete -F _ots_complete ots bin/ots ./bin/ots
        BASH
      end
    end

    register 'completion', CompletionCommand
  end
end
