# apps/web/auth/config/features/account_management.rb

module Auth
  module Config
    module Features
      module AccountManagement
        def self.configure(rodauth_config)
          rodauth_config.instance_eval do
            # Account management features
            features = [:create_account, :close_account, :change_password, :reset_password]

            # Only enable verify_account in non-test environments
            features << :verify_account unless ENV['RACK_ENV'] == 'test'

            enable *features

            # Password requirements
            password_minimum_length 8

            # Disable password confirmation field requirement
            # UI sends single password field, not password + confirmation
            require_password_confirmation? false

            # Password is set during account creation, not during verification
            # This prevents verify_account from requiring password fields
            verify_account_set_password? false

            # Custom error messages for account creation
            # Default Rodauth message: "There was an error creating your account"
            # This is generated by Rodauth internally, not from our codebase
            create_account_error_flash 'Unable to create account'
          end
        end
      end
    end
  end
end
