# .github/actions/run-ruby-tests/action.yml
---
# ==============================================================================
# Run Ruby Tests - Composite Action
# ==============================================================================
# Version: 2.1.0
# Repository: onetimesecret/onetimesecret
#
# Executes Ruby test suites via rake tasks with configurable authentication
# modes. Both RSpec and Tryouts run through rake for consistent process
# isolation. Generates GitHub job summaries with test results.
#
# Usage:
#   # Unit tests (RSpec + Tryouts)
#   - uses: ./.github/actions/run-ruby-tests
#     with:
#       test-type: 'unit'
#       auth-mode: 'simple'
#
#   # Integration tests (simple mode)
#   - uses: ./.github/actions/run-ruby-tests
#     with:
#       test-type: 'integration'
#       auth-mode: 'simple'
#
#   # Integration tests (full mode with PostgreSQL)
#   - uses: ./.github/actions/run-ruby-tests
#     with:
#       test-type: 'integration'
#       auth-mode: 'full'
#       auth-database-url: 'postgresql://...'
#       rspec-tag: 'postgres_database'
#
# Rake Tasks Used:
#   RSpec:
#   - spec:fast                  - Unit tests (unit, onetime, cli, apps)
#   - spec:integration:simple    - Simple mode integration
#   - spec:integration:full      - Full mode with SQLite
#   - spec:integration:full:postgres - Full mode with PostgreSQL
#   - spec:integration:disabled  - Disabled mode integration
#
#   Tryouts:
#   - try:unit                   - Unit tryouts (try/unit, try/system, try/security, try/features)
#   - try:integration:simple     - Integration tryouts (simple mode only)
#
# Changelog:
#   2.1.0 - Use spec:fast for unit tests; leverage auto-discovery
#   2.0.0 - Switch to rake tasks; remove rspec-paths input
#   1.0.0 - Initial release with RSpec/Tryouts support and job summaries
# ==============================================================================

name: Run Ruby Tests
description: |
  Runs Ruby tests via rake tasks with configurable auth mode and test type.
  Generates job summary with test results.

inputs:
  test-type:
    description: 'Type of tests to run: unit or integration'
    required: true
  auth-mode:
    description: 'Authentication mode: simple, full, or disabled'
    required: false
    default: 'simple'
  redis-url:
    description: 'Redis connection URL'
    required: false
    default: 'redis://127.0.0.1:2121/0'
  auth-database-url:
    description: 'Auth database URL (for full mode)'
    required: false
    default: ''
  auth-database-url-migrations:
    description: 'Auth database URL for migrations (elevated privileges)'
    required: false
    default: ''
  rspec-tag:
    description: 'RSpec tag for special cases (e.g., postgres_database)'
    required: false
    default: ''
  results-file:
    description: 'Name for the RSpec JSON results file'
    required: false
    default: 'rspec_results.json'
  debug-enabled:
    description: 'Enable tmate debugging session'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3
      if: inputs.debug-enabled == 'true'
      with:
        detached: true

    - name: Determine rake tasks
      id: rake-tasks
      shell: bash
      run: |
        TEST_TYPE="${{ inputs.test-type }}"
        AUTH_MODE="${{ inputs.auth-mode }}"
        RSPEC_TAG="${{ inputs.rspec-tag }}"

        # Determine RSpec task
        if [ "$TEST_TYPE" == "unit" ]; then
          echo "rspec-task=spec:fast" >> $GITHUB_OUTPUT
          echo "tryouts-task=try:unit" >> $GITHUB_OUTPUT
        elif [ "$TEST_TYPE" == "integration" ]; then
          if [ "$AUTH_MODE" == "full" ] && [ "$RSPEC_TAG" == "postgres_database" ]; then
            echo "rspec-task=spec:integration:full:postgres" >> $GITHUB_OUTPUT
          else
            echo "rspec-task=spec:integration:$AUTH_MODE" >> $GITHUB_OUTPUT
          fi
          # Tryouts integration only runs in simple mode
          if [ "$AUTH_MODE" == "simple" ]; then
            echo "tryouts-task=try:integration:simple" >> $GITHUB_OUTPUT
          else
            echo "tryouts-task=" >> $GITHUB_OUTPUT
          fi
        else
          echo "::error::Unknown test-type: $TEST_TYPE"
          exit 1
        fi

    - name: Run Tryouts via rake
      if: steps.rake-tasks.outputs.tryouts-task != ''
      shell: bash
      env:
        REDIS_URL: ${{ inputs.redis-url }}
        RACK_ENV: 'test'
        AUTHENTICATION_MODE: ${{ inputs.auth-mode }}
        AUTH_DATABASE_URL: ${{ inputs.auth-database-url }}
        AUTH_DATABASE_URL_MIGRATIONS: ${{ inputs.auth-database-url-migrations }}
      run: |
        set -e
        echo "Running rake ${{ steps.rake-tasks.outputs.tryouts-task }}..."
        bundle exec rake ${{ steps.rake-tasks.outputs.tryouts-task }}

    - name: Run RSpec via rake
      shell: bash
      env:
        REDIS_URL: ${{ inputs.redis-url }}
        RACK_ENV: 'test'
        AUTHENTICATION_MODE: ${{ inputs.auth-mode }}
        AUTH_DATABASE_URL: ${{ inputs.auth-database-url }}
        AUTH_DATABASE_URL_MIGRATIONS: ${{ inputs.auth-database-url-migrations }}
        RSPEC_OUTPUT_FILE: tmp/${{ inputs.results-file }}
      run: |
        set -e
        mkdir -p tmp
        echo "Running rake ${{ steps.rake-tasks.outputs.rspec-task }}..."
        bundle exec rake ${{ steps.rake-tasks.outputs.rspec-task }}

    - name: Generate job summary
      if: always()
      shell: bash
      run: |
        echo "## Ruby Test Results (${{ inputs.auth-mode }} mode)" >> $GITHUB_STEP_SUMMARY

        if [ -n "${{ steps.rake-tasks.outputs.tryouts-task }}" ]; then
          echo "### Tryouts" >> $GITHUB_STEP_SUMMARY
          echo "- Task: \`${{ steps.rake-tasks.outputs.tryouts-task }}\`" >> $GITHUB_STEP_SUMMARY
        fi

        if [ -f "tmp/${{ inputs.results-file }}" ]; then
          echo "### RSpec" >> $GITHUB_STEP_SUMMARY
          echo "- Task: \`${{ steps.rake-tasks.outputs.rspec-task }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Total: $(jq '.summary.example_count' "tmp/${{ inputs.results-file }}")" >> $GITHUB_STEP_SUMMARY
          echo "- Failures: $(jq '.summary.failure_count' "tmp/${{ inputs.results-file }}")" >> $GITHUB_STEP_SUMMARY
        fi
