# frozen_string_literal: true

source 'https://rubygems.org'

gem 'base64'  # Required for Ruby 3.4+
gem 'json_schemer', '~> 2.0'
gem 'kiba', '~> 4.0'
gem 'oj', '~> 3.16'  # JSON serialization for Familia v2 compatibility
gem 'redis', '~> 5.0'

group :development, :test do
  gem 'rspec', '~> 3.12'
end
