# lib/onetime/models/organization.rb
#
# frozen_string_literal: true

require 'rack/utils'

module Onetime
  # Organization Model
  #
  # Phase 1 MVP: Nearly invisible billing/ownership container
  # Appears ONLY in account settings, not in secret creation flows
  #
  # Uses Familia v2.0.0-pre22 participates_in for bidirectional relationships:
  # - Customer.participates_in :Organization, :members (defined in customer.rb)
  # - Auto-generates: org.members (sorted_set), customer.organization_instances, etc.
  #
  class Organization < Familia::Horreum

    using Familia::Refinements::TimeLiterals

    prefix :org

    class_sorted_set :values

    feature :safe_dump

    feature :relationships
    feature :object_identifier
    feature :external_identifier, format: 'on%<id>s'
    feature :required_fields
    feature :with_organization_billing
    feature :with_stripe_account
    feature :with_capabilities

    identifier_field :orgid

    # Unique index for contact email (prevents duplicates, enables fast lookups)
    unique_index :contact_email, :contact_email_index

    # Core fields
    field :orgid
    field :display_name
    field :description
    field :owner_id       # custid of organization owner
    field :contact_email  # Primary billing/contact email
    field :is_default     # Boolean: true for auto-created workspace (prevents deletion)

    hashkey :urls

    # Familia v2 relationships - AUTO-GENERATED collections:
    # - members (from Customer.participates_in Organization, :members)
    # - teams (from Team.participates_in Organization, :teams)
    # DO NOT manually define sorted_set :members or sorted_set :teams here

    def init
      @orgid ||= Familia.generate_id
      @planid ||= 'free'  # Default to free plan
      nil
    end

    # Owner management
    def owner
      Onetime::Customer.load(owner_id) if owner_id
    end

    def owner?(customer)
      customer && customer.custid == owner_id
    end

    # Member management - Familia v2 auto-generated methods wrapper
    # The members sorted_set is auto-generated by Customer.participates_in Organization, :members
    # The add/remove methods are on the CUSTOMER, not the organization

    def add_member(customer)
      # Use Familia v2 auto-generated method ON THE CUSTOMER
      customer.add_to_organization_members(self)
    end

    def remove_member(customer)
      # Use Familia v2 auto-generated method ON THE CUSTOMER
      customer.remove_from_organization_members(self)
    end

    def member?(customer)
      return false unless customer
      # members is auto-generated sorted_set
      members.member?(customer.objid)
    end

    def member_count
      # members is auto-generated sorted_set
      members.size
    end

    def list_members
      # Bulk loading with auto-generated members collection
      Customer.load_multi(members.to_a)
    end

    # Authorization helpers
    def can_modify?(current_user)
      owner?(current_user)
    end

    def can_delete?(current_user)
      # Default workspaces cannot be deleted (would break user's account)
      return false if is_default
      # Otherwise, only owners can delete
      owner?(current_user)
    end

    class << self
      def create!(display_name, owner_customer, contact_email = nil)
        raise Onetime::Problem, 'Owner required' if owner_customer.nil?

        display_name = display_name.to_s.strip
        raise Onetime::Problem, 'Display name required' if display_name.empty?

        contact_email = contact_email.to_s.strip
        # contact_email is optional - can be set later for billing
        if !contact_email.empty? && contact_email_exists?(contact_email)
          raise Onetime::Problem, 'Organization exists for that email address'
        end

        org = new(
          display_name: display_name,
          owner_id: owner_customer.custid,
          contact_email: contact_email.empty? ? nil : contact_email
        )
        org.save

        # Use Familia v2 auto-generated method to add owner as first member
        owner_customer.add_to_organization_members(org)

        OT.ld "[Organization.create!] orgid: #{org.orgid}, owner: #{owner_customer.custid}"

        org
      end

      def contact_email_exists?(email)
        # Use unique_index auto-generated finder for O(1) lookup
        !find_by_contact_email(email).nil?
      end
    end
  end
end
