# lib/onetime/models/team.rb

require 'rack/utils'

module Onetime
  # Team Model (aka Group)
  #
  class Team < Familia::Horreum

    using Familia::Refinements::TimeLiterals

    feature :safe_dump

    feature :relationships
    feature :object_identifier
    feature :external_identifier, format: 'tm%<id>s'
    feature :required_fields

    prefix :team

    identifier_field :objid

    # Familia v2 relationships - AUTO-GENERATED from Customer.participates_in Team, :members
    # This creates: team.members (sorted_set), team.add_members_instance, team.remove_members_instance
    # DO NOT manually define sorted_set :members here

    field :teamid
    field :display_name
    field :description
    field :owner_id       # custid of team owner
    field :org_id         # Optional reference to Organization.objid

    # Team participates in Organization teams collection
    participates_in :Organization, :teams

    def init
      self.teamid ||= objid
      nil
    end

    # Owner management
    def owner
      Onetime::Customer.load(owner_id) if owner_id
    end

    def owner?(customer)
      customer && customer.custid == owner_id
    end

    # Member management - Familia v2 auto-generated methods wrapper
    # The members sorted_set is auto-generated by Customer.participates_in Team, :members
    # The add/remove methods are on the CUSTOMER, not the team

    def add_member(customer, role = 'member')
      # Use Familia v2 auto-generated method ON THE CUSTOMER
      customer.add_to_team_members(self)
    end

    def remove_member(customer)
      # Use Familia v2 auto-generated method ON THE CUSTOMER
      customer.remove_from_team_members(self)
    end

    def member?(customer)
      return false unless customer
      # members is auto-generated sorted_set
      members.member?(customer.objid)
    end

    def member_count
      # members is auto-generated sorted_set
      members.size
    end

    def list_members
      # Bulk loading with auto-generated members collection
      Customer.load_multi(members.to_a)
    end

    # Authorization helpers
    def can_modify?(current_user)
      owner?(current_user)
    end

    def can_delete?(current_user)
      owner?(current_user)
    end

    class << self
      def create!(display_name, owner_customer, org_id = nil)
        raise Onetime::Problem, 'Owner required' if owner_customer.nil?
        display_name = display_name.to_s.strip
        raise Onetime::Problem, 'Display name required' if display_name.empty?

        team = new(
          display_name: display_name,
          owner_id: owner_customer.custid,
          org_id: org_id
        )
        team.save

        # Use Familia v2 auto-generated method to add owner as first member
        owner_customer.add_to_team_members(team)

        # If org provided, add team to organization
        if org_id && (org = Organization.load(org_id))
          team.add_to_organization_teams(org)
        end

        OT.ld "[Team.create!] teamid: #{team.teamid}, owner: #{owner_customer.custid}, org: #{org_id}"
        team
      end
    end
  end
end
