# lib/onetime/models/team.rb
#
# frozen_string_literal: true

require 'rack/utils'

module Onetime
  # Team Model (aka Group)
  #
  # Features are loaded from lib/onetime/models/team/features.rb
  #
  # Primary Keys & Identifiers:
  #   - objid - Primary key (UUID), internal
  #   - extid - External identifier (e.g., tm%<id>s), user-facing
  #
  # Foreign Keys:
  #   - team_id (underscore) - Foreign key field, stores the objid value
  #   - All FK relationships use objid values for indexing
  #
  # API Layer:
  #   - Public URLs/APIs should use extid for user-facing references
  #   - Use find_by_extid(extid) to convert extid → object
  #   - Internally, relationships always use objid
  #
  # Logging:
  #   - Use extid. Don't log internal IDs.
  #
  # Easy way to remember: if you can see a UUID, it's an internal ID. If
  # you can't, it's an external ID.
  #
  class Team < Familia::Horreum
    include Familia::Features::Autoloader

    using Familia::Refinements::TimeLiterals

    feature :safe_dump_fields

    feature :relationships
    feature :object_identifier
    feature :external_identifier, format: 'tm%<id>s'
    feature :required_fields

    prefix :team

    identifier_field :objid

    # CRITICAL: DO NOT manually define sorted_set :members
    # Familia v2 relationships - Explicitly declare collection for participates_in
    # This is populated by Customer.participates_in Team, :members
    # #sorted_set :members

    field :display_name
    field :description
    field :owner_id       # custid of team owner
    field :org_id         # Optional reference to Organization.objid
    field :is_default     # Boolean: true for auto-created workspace (prevents deletion)

    # Team participates in Organization teams collection
    participates_in :Organization, :teams

    def init
      nil
    end

    # Underscore means foreign key. This is a convenience method for semantic
    # clarity when comparing, e.g. team.team_id == entity.team_id
    def team_id
      objid
    end

    # Owner management
    def owner
      Onetime::Customer.load(owner_id) if owner_id
    end

    def owner?(customer)
      customer && customer.user_id == owner_id
    end

    # Member management - Familia v2 auto-generated methods wrapper
    # The members sorted_set is auto-generated by Customer.participates_in Team, :members

    def add_member(customer, _role = 'member')
      # Use Familia v2 bidirectional add: updates BOTH team.members AND customer.team_instances
      add_members_instance(customer)
    end

    def remove_member(customer)
      # Use Familia v2 bidirectional remove: updates BOTH team.members AND customer.team_instances
      remove_members_instance(customer)
    end

    def member?(customer)
      return false unless customer

      # members is auto-generated sorted_set
      members.member?(customer.objid)
    end

    def member_count
      # members is auto-generated sorted_set
      members.size
    end

    def list_members
      # Bulk loading with auto-generated members collection
      Customer.load_multi(members.to_a)
    end

    # Authorization helpers
    def can_modify?(current_user)
      owner?(current_user)
    end

    def can_delete?(current_user)
      # Default workspaces cannot be deleted (would break user's account)
      return false if is_default

      # Otherwise, only owners can delete
      owner?(current_user)
    end

    class << self
      def create!(display_name, owner_customer, org_id = nil)
        raise Onetime::Problem, 'Owner required' if owner_customer.nil?

        display_name = display_name.to_s.strip
        raise Onetime::Problem, 'Display name required' if display_name.empty?

        team = new(
          display_name: display_name,
          owner_id: owner_customer.user_id,
          org_id: org_id,
        )
        team.save

        # Use Familia v2 auto-generated method to add owner as first member
        owner_customer.add_to_team_members(team)

        # If org provided, add team to organization
        if org_id && (org = Organization.load(org_id))
          team.add_to_organization_teams(org)
        end

        OT.ld "[Team.create!] team_id: #{team.team_id}, owner: #{owner_customer.user_id}, org: #{org_id}"
        team
      end

      def count
        instances.count # e.g. zcard dbkey
      end
    end
  end
end
