# 2025-06-02
#
# Ticket #1452
#
# Configuration mapping for splitting monolithic config into static and dynamic parts
# Static: Lives in etc/config.yaml
# Dynamic: Lives in the database via V2::SystemSettings model.

mappings:
  static:
    # Core site configuration
    - from: "site.host"
      to: "site.host"
    - from: "site.ssl"
      to: "site.ssl"
    - from: "site.secret"
      to: "site.secret"

    # Authentication core settings
    - from: "site.authentication.enabled"
      to: "site.authentication.enabled"
    - from: "site.authentication.colonels"
      to: "site.authentication.colonels"

    # Security settings
    - from: "site.authenticity"
      to: "site.authenticity"

    # Redis configuration
    - from: "redis.uri"
      to: "storage.db.connection.url"
    - from: "redis.dbs"
      to: "storage.db.database_mapping"

    # Email configuration
    - from: "emailer"
      to: "mail.connection"

    # Logging configuration
    - from: "logging"
      to: "logging"

    # Development settings
    - from: "development"
      to: "development"

    # Experimental features (runtime toggleable)
    - from: "experimental.allow_nil_global_secret"
      to: "experimental.allow_nil_global_secret"
    - from: "experimental.rotated_secrets"
      to: "experimental.rotated_secrets"
    - from: "experimental.freeze_app"
      to: "experimental.freeze_app"
    - from: "experimental.middleware."
      to: "site.middleware"

  dynamic:
    # UI interface settings
    - from: "site.interface.ui"
      to: "user_interface"

    - from: "site.authentication.signup"
      to: "user_interface.signup"
    - from: "site.authentication.signin"
      to: "user_interface.signin"
    - from: "site.authentication.verify"
      to: "user_interface.autoverify"

    # API interface settings
    - from: "site.interface.api"
      to: "api"

    # Secret options
    - from: "site.secret_options"
      to: "secret_options"

    # Feature flags
    - from: "features"
      to: "features"

    # Region
    - from: "site.regions"
      to: "features.regions"

    # Plans
    - from: "site.plans"
      to: "features.plans"

    # Domains
    - from: "site.domains"
      to: "features.domains"

    # Diagnostics
    - from: "diagnostics"
      to: "diagnostics"

    # Limits
    - from: "limits"
      to: "limits"

    # i18n
    - from: "internationalization"
      to: "features.internationalization"

    # Mail validation
    - from: "mail.truemail"
      to: "mail.validation.recipients"
    - from: "mail.truemail"
      to: "mail.validation.accounts"
