---
:site:
  :host: '127.0.0.1:3000'
  :domains:
    :enabled: false
    # The default domain used for link URLs. When not set or empty,
    # site.host is used.
    :default: <%= ENV['DEFAULT_DOMAIN'] || nil %>
    # The cluster type determines how the application will support
    # multiple domains. The default is nil which means that the
    # application itself is responsible for handling multiple domains.
    :cluster:
      :type: <%= ENV['CLUSTER_TYPE'] || nil %>
  # Turns https/http on or off when generating links
  :ssl: true
  :secret: SuP0r_53cRU7
  # Registration and Authentication settings
  :authentication:
    # Can be disabled altogether, including API authentication.
    :enabled: true
    # Allow users to create accounts. This can be disabled if you plan
    # to create accounts manually or enable during setup when accounts
    # can be created and then disabled to prevent any new users from
    # creating accounts.
    :signup: true
    # Generally if you allow registration, you allow signin. But there
    # are circumstances where it's helpful to turn off authentication
    # temporarily.
    :signin: true
    # By default, new accounts need to verify their email address before
    # they can sign in. This is a security measure to prevent spamming
    # and abuse of the system. If you're running a private instance or
    # an instance for your team or company, you can disable this feature
    # to make it easier for users to sign in.
    :autoverify: false
  :authenticity:
    :type: <%= ENV['AUTHENTICITY_TYPE'] || 'altcha' %>
    :secret_key: <%= ENV['AUTHENTICITY_SECRET_KEY'] || 'your-secret-key' %>
  :plans:
    :enabled: false
:redis:
  :uri: 'redis://CHANGEME@127.0.0.1:6379/0'
  :config: ./try/redis.conf
:colonels:
  - 'CHANGEME@EXAMPLE.com'
:emailer:
  :mode: :smtp
  :from: CHANGEME@example.com
  :fromname: Jan
  :host: localhost
  :port: 587
  :tls: true
  :user:
  :pass:
  :auth: login
:mail:
  :truemail:
    # Available validation types: :regex, :mx, :mx_blacklist, :smtp
    :default_validation_type: :mx
    # Required for :smtp validation
    :verifier_email: <%= ENV['VERIFIER_EMAIL'] || 'CHANGEME@example.com' %>
    :verifier_domain: <%= ENV['VERIFIER_DOMAIN'] || 'example.com' %>
    :connection_timeout: 1
    :response_timeout: 1
    :connection_attempts: 1
    :validation_type_for:
      'example.com': :regex
    # Truemail will only validate email addresses that match the
    # domains listed in :allowed_domains. If the domain is not
    # listed, the email address will always be considered invalid.
    :allowed_domains_only: false
    #
    # Email addresses in this list will always be valid.
    #:allowed_emails: []
    #
    # Email addresses in this list will always be invalid.
    #:blocked_emails: []
    #
    # Addresses with these domains will always be valid
    #:allowed_domains: []
    #
    # Addresses with these domains will always be invalid
    #:blocked_domains: []
    #
    # Exclude these IP addresses from the MX lookup process.
    #:blocked_mx_ip_addresses: []
    #
    # Name servers to use for MX et al record lookup.
    # Default is CloudFlare, Google, Oracle/OpenDNS servers.
    :dns:
      - 1.1.1.1
      - 8.8.4.4
      - 208.67.220.220
    #:smtp_port: 25
    #
    # End smtp validation after the first invalid response rather than
    # retrying, followed by trying the next server. Can reduce the time
    # time to validate an email address, but may not catch all issues.
    :smtp_fail_fast: true
    #
    # Parse the content of the SMTP error message to determine if the
    # email address is valid. This can be useful for some SMTP servers
    # that don't return exact answers.
    :smtp_safe_check: true
    #
    # Whether to disable the RFC MX lookup flow. When true, only DNS
    # validation will be performed on MX and Null MX records.
    :not_rfc_mx_lookup_flow: false
    #
    # Override default regular expression pattern for email addresses
    # and/or the content in SMTP error messages.
    #:email_pattern: /regex_pattern/
    #:smtp_error_body_pattern: /regex_pattern/
    #
    # Log to the console, a file, or both. The ruby process must have
    # write access to the log file. The log file will be created if it
    # does not exist. Log file rotation is not handled by the app.
    :logger:
      # One of: :error (default), :unrecognized_error,
      # :recognized_error, :all.
      tracking_event: :unrecognized_error
      stdout: true
      # log_absolute_path: '/home/app/log/truemail.log'
:locales:
  - en
  - ar
  - bg
  - ca_ES
  - cn
  - cs
  - da_DK
  - de
  - el_GR
  - en
  - es
  - fr
  - fr_FR
  - he
  - hu
  - it_IT
  - nl
  - pl
  - pt_BR
  - ru
  - sl_SI
  - sv_SE
  - tr
  - vi
:services:
  :sentry:
    :dsn: <%= ENV['SENTRY_DSN'] || 'CHANGEME' %>
    :enabled: <%= !ENV['SENTRY_DSN'].nil? %>
:limits:
  :create_secret: 250
  :create_account: 10
  :update_account: 10
  :email_recipient: 50
  :send_feedback: 10
  :authenticate_session: 5
  :get_page: 500
  :dashboard: 1000
  :failed_passphrase: 5
  :show_metadata: 1000
  :show_secret: 1000
  :burn_secret: 1000
  :destroy_account: 5
  :forgot_password_request: 2
  :forgot_password_reset: 3
  :generate_apitoken: 3
:development:
  :enabled: <%= ['development', 'dev'].include?(ENV['RACK_ENV']) %>
  :debug: <%= ['true', '1', 'yes'].include?(ENV['ONETIME_DEBUG']) %>
  :frontend_host: <%= ENV['FRONTEND_HOST'] || 'http://localhost:5173' %>
