# lib/onetime/initializers/configure_rhales.rb
#
# frozen_string_literal: true

require 'rhales'

# Session wrapper that adapts Rack session to Rhales expectations
#
# Rhales expects sessions to respond to #authenticated?, but Rack sessions don't have this method.
# This wrapper delegates everything to the underlying session while providing the authentication
# interface that Rhales needs.
class OnetimeSessionAdapter < SimpleDelegator
  def authenticated?
    # Otto authentication logic: requires session['authenticated'] == true AND external_id present
    self['authenticated'] == true && !self['external_id'].to_s.empty?
  end
end

module Onetime
  module Initializers
    # ConfigureRhales initializer
    #
    # Configures Rhales framework for Onetime Secret. Sets up CSP nonce usage,
    # hydration script injection for Vue.js SPA, and template paths.
    #
    # This initializer primarily configures an external library and doesn't set
    # runtime state that needs to be tracked.
    #
    class ConfigureRhales < Onetime::Boot::Initializer
      @provides = [:rhales]

      def execute(_context)
        # Set Rhales logger if supported (Rhales 0.5+)
        # Uses respond_to? check for backward compatibility with earlier versions
        if Rhales.respond_to?(:logger=)
          Rhales.logger = Onetime.rhales_logger
        end

        # Guard against multiple configuration attempts
        # Rhales.configure freezes the config after first call
        return if Rhales.configuration.frozen?

        Rhales.configure do |config|
          # Use existing nonce from Onetime Secret middleware
          # This ensures all script tags use the same CSP nonce
          config.nonce_header_name = 'onetime.nonce'

          # Inject hydration scripts in <head> before Vue.js initialization
          # :earliest ensures window.__ONETIME_STATE__ is available when Vue mounts
          config.hydration.injection_strategy = :earliest

          # Schema is source of truth (production mindset)
          # Schema defined in apps/web/core/templates/index.rue
          config.hydration_authority       = :schema  # default
          config.hydration_mismatch_format = :compact  # or :multiline, :compact, :sidebyside, :json

          # Vue.js mounts to #app, ensure hydration happens before mount
          config.hydration.mount_point_selectors = ['#app']

          # Set template paths to match existing structure
          templates_dir         = File.join(OT::HOME, 'apps', 'web', 'core', 'templates')
          config.template_paths = [templates_dir]

          # Suppress unescaped variable warnings for known safe HTML variables
          # vite_assets_html contains <script> and <link> tags generated by Vite
          config.allowed_unescaped_variables = ['vite_assets_html']
        end
      end
    end
  end
end
