<template>

<div class="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-12">
  <h2 class="text-3xl font-bold text-left text-gray-900 dark:text-white mb-8">
    <span class="text-xl font-semibold text-gray-700 dark:text-gray-300">AI-Generated Testimonials</span>
    <br>
    <span>What leading AI might say about us:</span>
  </h2>

  <div class="bg-white dark:bg-gray-800 shadow-lg rounded-lg overflow-hidden">
    <div class="p-6 sm:p-8">
      <svg class="w-5 h-5 text-brand-500 mb-4" fill="currentColor" viewBox="0 0 24 24" width="20" height="20">
        <path d="M14.017 21v-7.391c0-5.704 3.731-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 9-10.609l.996 2.151c-2.433.917-3.996 3.638-3.996 5.849h3.983v10h-9.983z" />
      </svg>

      <p class="text-lg leading-relaxed text-gray-700 dark:text-gray-300 mb-6 italic">
        "{{ props.testimonial.quote }}"
      </p>

      <div class="flex items-center justify-between">
        <div>
          <p class="font-semibold text-gray-900 dark:text-white">
            {{ props.testimonial.name }}
          </p>
          <p class="text-sm text-gray-600 dark:text-gray-400">
            {{ props.testimonial.company }}
          </p>
        </div>

        <div class="flex items-center">
          <StarsRating :stars="props.testimonial.stars" />
        </div>
      </div>
    </div>

    <div class="bg-gray-100 dark:bg-gray-700 px-6 py-4">
      <p class="text-sm text-gray-600 dark:text-gray-400 italic">
        Note: <span class="">This quote was generated by <a href="https://www.anthropic.com/news/claude-3-5-sonnet" class="underline" rel="noopener noreferrer" target="_blank">Claude 3.5</a></span>. It was based on the content of the page and does not represent an actual person or company.
      </p>
    </div>
  </div>
</div>

</template>

<script setup lang="ts">
import StarsRating from "@/components/StarsRating.vue";
import { Testimonial } from "@/sources/testimonials";

// Define props using defineProps
const props = defineProps<{
  testimonial: Testimonial;
}>();

</script>
