# apps/web/core/spec/views/base_spec.rb
#
# frozen_string_literal: true

require_relative '../../../../../spec/spec_helper'

require_relative '../../views/base'
require_relative '../../views/serializers'

# Tests for Core::Views::BaseView and its serializers.
# BaseView expects a single Rack::Request argument and extracts session/customer
# from req.env['otto.strategy_result'].
RSpec.describe Core::Views::BaseView do
  subject { described_class.new(rack_request) }

  include_context 'rack_test_context'
  include_context 'view_test_context'

  before(:all) do
    described_class.use_serializers(
      Core::Views::ConfigSerializer,
      Core::Views::AuthenticationSerializer,
      Core::Views::DomainSerializer,
      Core::Views::I18nSerializer,
      Core::Views::MessagesSerializer,
      Core::Views::SystemSerializer,
    )
  end

  before do
    allow(OT).to receive('default_locale').and_return('en')
    allow(OT).to receive('fallback_locale').and_return('en')
    allow(OT).to receive('supported_locales').and_return(['en'])
    allow(OT).to receive('i18n_enabled').and_return(true)

    allow(OT).to receive('locales').and_return({
      'en' => {
        web: {
          COMMON: {
            description: 'Test Description',
            keywords: 'test,keywords',
          },
        },
      },
    },
                                              )
  end

  describe '#initialize' do
    it 'sets basic template variables' do
      expect(subject.view_vars['description']).to eq('Test Description')
      expect(subject.view_vars['keywords']).to eq('test,keywords')
      # page_title falls through display_domain -> brand_product_name (the
      # legacy site_name tier was retired in #3612); the test config stubs
      # neither, so it resolves to the neutral NEUTRAL_PRODUCT_NAME terminal —
      # the server-rendered <title> must never be empty, and never 'OTS'.
      expect(subject.view_vars['page_title']).to eq('Secure Links')
    end

    it 'initializes JavaScript variables' do
      vars = subject.serialized_data
      expect(vars['authenticated']).to be true
      expect(vars['custid']).to eq('test@example.com')
      expect(vars['email']).to eq('test@example.com')
      # Shrimp is a masked CSRF token generated by Rack::Protection::AuthenticityToken
      # The masked token is base64-encoded and different from the raw session[:csrf]
      expect(vars['shrimp']).to be_a(String)
      expect(vars['shrimp']).not_to be_empty
      expect(vars['shrimp']).to match(/\A[A-Za-z0-9+\/=_-]+\z/) # base64 format
    end

    it 'includes authentication configuration' do
      expect(subject.serialized_data['authentication']).to include(
        'enabled' => true,
        'signup' => true,
      )
    end

    # ttl_max_anonymous is not raw config: ConfigSerializer appends the
    # request-host guest ceiling so the duration dropdown matches enforcement.
    # This canonical-host fixture receives the configured 7-day default; custom
    # hosts receive the domain owner organization's plan lifetime.
    it 'includes secret options plus the guest TTL ceiling' do
      expect(subject.serialized_data['secret_options']).to eq({
        'default_ttl' => 86_400,
        'ttl_options' => [3600, 86_400],
        # Effective ceiling also includes ttl_options.max (one day here).
        'ttl_max_anonymous' => 86_400,
      },
                                                             )
    end

    context 'with development mode' do
      let(:config) do
        super().merge(
          'development' => {
            'enabled' => true,
            'frontend_host' => 'http://localhost:5173',
          },
        )
      end

      it 'sets development-specific variables' do
        expect(subject.view_vars['frontend_host']).to eq('http://localhost:5173')
        expect(subject.view_vars['frontend_development']).to be true
      end
    end

    context 'with anonymous user' do
      let(:session) do
        {
          'csrf' => 'test_shrimp',
          'awaiting_mfa' => false,
          'authenticated' => false,
        }
      end

      let(:customer) do
        cust = instance_double(Onetime::Customer,
          anonymous?: true,
          planid: 'anonymous',
          custid: nil,
          email: nil,
          created: nil,
          safe_dump: {
            'identifier' => 'anon',
            'custid' => 'anon',
            'role' => 'customer',
            'verified' => nil,
            'last_login' => nil,
            'locale' => '',
            'updated' => nil,
            'created' => nil,
            'stripe_customer_id' => nil,
            'stripe_subscription_id' => nil,
            'stripe_checkout_email' => nil,
            'secrets_created' => '0',
            'secrets_burned' => '0',
            'secrets_shared' => '0',
            'emails_sent' => '0',
            'active' => false,
          },
        )
        allow(cust).to receive(:role?).and_return(false)
        cust
      end

      let(:strategy_result) do
        instance_double('Otto::Security::Authentication::StrategyResult',
          session: session,
          user: customer,
          authenticated?: false,
          metadata: {})
      end

      it 'sets appropriate anonymous state' do
        vars = subject.serialized_data
        expect(vars['auth_status']).to eq('anonymous')
        expect(vars['authenticated']).to be false
        expect(vars['custid']).to be_nil
        expect(vars['email']).to be_nil
      end
    end
  end

  describe 'has_brand_color contract' do
    # has_brand_color drives the conditional render of the brand-colored
    # head tags (mask-icon + light theme-color) in head-base.rue. It MUST be
    # false when no brand primary_color is configured so unbranded
    # deployments omit those tags (and the frontend falls through to
    # NEUTRAL_BRAND_DEFAULTS), and true when a color is configured.
    #
    # See: apps/web/core/views/helpers/initialize_view_vars.rb
    #      apps/web/core/templates/partials/head-base.rue
    #      e2e/all/brand-customization.spec.ts

    context 'when no brand primary_color is configured (unbranded)' do
      it 'sets has_brand_color to false' do
        expect(subject.view_vars['has_brand_color']).to be false
      end

      it 'leaves brand_primary_color nil' do
        expect(subject.view_vars['brand_primary_color']).to be_nil
      end
    end

    context 'when brand primary_color is an empty/whitespace string' do
      let(:config) do
        super().merge('brand' => { 'primary_color' => '   ' })
      end

      it 'sets has_brand_color to false' do
        expect(subject.view_vars['has_brand_color']).to be false
      end
    end

    context 'when a brand primary_color is configured (branded)' do
      let(:config) do
        super().merge('brand' => { 'primary_color' => '#112233' })
      end

      it 'sets has_brand_color to true' do
        expect(subject.view_vars['has_brand_color']).to be true
      end

      it 'exposes the configured brand_primary_color' do
        expect(subject.view_vars['brand_primary_color']).to eq('#112233')
      end
    end
  end

  describe '#initialize error-recovery path (no strategy_result)' do
    # When Otto has not run auth (500-style handler entry), the view must not
    # project identity from the raw Rack session. Otherwise the evaluator
    # would materialize a Customer from session['external_id'] on the error
    # response, and serializers reading @cust would leak custid/email on
    # pages that historically answered as anonymous.
    let(:authenticated_session) do
      {
        'csrf'             => 'test_shrimp',
        'account_id'       => 'test@example.com',
        'email'            => 'test@example.com',
        'external_id'      => 'ur_error_recovery',
        'authenticated'    => true,
        'authenticated_at' => Time.now.to_i,
        'awaiting_mfa'     => false,
        Onetime::SessionSurface::KEY => { 'kind' => 'canonical' },
      }
    end

    let(:rack_request) do
      # otto.strategy_result deliberately absent.
      env = {
        'REMOTE_ADDR'             => '127.0.0.1',
        'HTTP_HOST'               => 'example.com',
        'rack.session'            => authenticated_session,
        'otto.locale'             => 'en',
        'onetime.domain_strategy' => :canonical,
        'onetime.nonce'           => nil,
      }

      request = instance_double('Rack::Request')
      allow(request).to receive(:env).and_return(env)
      allow(request).to receive(:nil?).and_return(false)
      allow(request).to receive(:session).and_return(authenticated_session)
      request
    end

    it 'leaves @cust nil even when the raw session claims authentication' do
      # The evaluator MUST NOT be consulted on this path; if it is, it means
      # identity can hydrate from a session on an error response.
      expect(Onetime::CustomerSessionEvaluator).not_to receive(:evaluate)

      view = described_class.new(rack_request)
      expect(view.cust).to be_nil
    end

    it 'still exposes the raw session (CSRF/messages remain reachable)' do
      view = described_class.new(rack_request)
      expect(view.sess).to be(authenticated_session)
    end

    # #4462: the server states what the client used to infer from
    # had_valid_session. The session names a customer this response cannot
    # vouch for, so the status is `unavailable`: no identity, and not a
    # sign-out either.
    it 'reports auth_status unavailable, with no identity, for a session that names a customer' do
      data = described_class.new(rack_request).serialized_data

      expect(data).to include(
        'auth_status' => 'unavailable',
        'authenticated' => false,
        'awaiting_mfa' => false,
        'cust' => nil,
      )
      expect(data['custid']).to be_nil
      expect(data['email']).to be_nil
    end

    it 'reports auth_status anonymous when the raw session names no customer' do
      authenticated_session.delete('external_id')

      expect(described_class.new(rack_request).serialized_data).to include(
        'auth_status' => 'anonymous',
        'authenticated' => false,
      )
    end
  end

  # ADR-046 / #4457. The view passes the middleware's allocation through only
  # for a payload that reports a session, and a failed allocation degrades the
  # hydration payload instead of failing the render.
  describe 'bootstrap snapshot ordering' do
    let(:allocation) do
      {
        epoch: '0123456789abcdef0123456789abcdef',
        version: '1758236400000001',
        generated_at: '2026-09-17T17:28:59.123456Z',
      }
    end

    let(:logger) { spy('session_logger') }

    before { allow(Onetime).to receive(:session_logger).and_return(logger) }

    it 'emits the pair the middleware allocated for an authenticated snapshot' do
      rack_request.env[Onetime::SnapshotOrdering::ENV_KEY] = allocation

      expect(subject.serialized_data).to include(
        'auth_status' => 'authenticated',
        'snapshot_epoch' => allocation[:epoch],
        'snapshot_version' => allocation[:version],
        'snapshot_generated_at' => allocation[:generated_at],
      )
    end

    it 'renders a degraded hydration payload when allocation failed: no pair, one diagnostic', :aggregate_failures do
      rack_request.env[Onetime::SnapshotOrdering::ENV_KEY] = { error: 'Redis::CannotConnectError' }
      rack_request.env['HTTP_X_REQUEST_ID']                = 'req-degraded'

      data = subject.serialized_data

      expect(data).to include('auth_status' => 'authenticated', 'authenticated' => true)
      expect(data.keys.grep(/\Asnapshot_/)).to be_empty
      expect(logger).to have_received(:warn).with(
        'Bootstrap snapshot serialized without ordering',
        { module: 'InitializeViewVars', error: 'Redis::CannotConnectError', request_id: 'req-degraded' },
      )
    end

    it 'never labels a payload that reports no session, even if an allocation exists' do
      rack_request.env[Onetime::SnapshotOrdering::ENV_KEY] = allocation
      session['authenticated']                             = false

      data = described_class.new(rack_request).serialized_data

      expect(data).to include('auth_status' => 'anonymous', 'authenticated' => false)
      expect(data.keys.grep(/\Asnapshot_/)).to be_empty
      expect(logger).not_to have_received(:warn).with('Bootstrap snapshot serialized without ordering', anything)
    end
  end

  describe '#add_message' do
    it 'adds info message to messages array' do
      subject.add_message('Test message')
      expect(subject.messages).to include({
        'type' => 'info',
        'content' => 'Test message',
      },
                                         )
    end

    it 'adds error message to messages array' do
      subject.add_error('Error message')
      expect(subject.messages).to include({
        'type' => 'error',
        'content' => 'Error message',
      },
                                         )
    end
  end

  context 'with diagnostics configuration' do
    context 'when diagnostics enabled with DSN provided' do
      before do
        allow(OT).to receive('d9s_enabled').and_return(true)
        allow(OT).to receive('conf').and_return(config.merge(
                                                  'diagnostics' => {
                                                    'sentry' => {
                                                      'frontend' => {
                                                        'dsn' => 'https://test-dsn@sentry.example.com/1',
                                                      },
                                                    },
                                                  },
                                                ),
                                               )
      end

      it 'sets diagnostic variables when enabled and DSN provided' do
        vars = subject.serialized_data
        expect(vars['diagnostics']['sentry']['dsn']).to eq('https://test-dsn@sentry.example.com/1')
        expect(vars['diagnostics']['sentry']).to include(
          'environment' => 'testing',
          'logErrors' => true,
          'maxBreadcrumbs' => 5,
          'sampleRate' => 1.0,
          'trackComponents' => true,
        )
        expect(vars['d9s_enabled']).to be true
      end
    end

    context 'when diagnostics disabled' do
      before do
        allow(OT).to receive('d9s_enabled').and_return(false)
        allow(OT).to receive('conf').and_return(config.merge(
                                                  'diagnostics' => {
                                                    'sentry' => {
                                                      'frontend' => {
                                                        'dsn' => nil,
                                                      },
                                                    },
                                                  },
                                                ),
                                               )
      end

      it 'sets diagnostic to disabled when DSN not provided' do
        vars = subject.serialized_data
        expect(vars['d9s_enabled']).to be false
        expect(vars['diagnostics']['sentry']['dsn']).to be_nil
        expect(vars['diagnostics']['sentry']).to include(
          'environment' => 'testing',
          'logErrors' => true,
          'maxBreadcrumbs' => 5,
          'sampleRate' => 1.0,
          'trackComponents' => true,
        )
      end
    end
  end

  context 'with security headers' do
    let(:rack_request) do
      env = {
        'REMOTE_ADDR' => '127.0.0.1',
        'HTTP_HOST' => 'example.com',
        'rack.session' => session,
        'otto.locale' => 'en',
        'otto.strategy_result' => strategy_result,
        'onetime.nonce' => 'test-nonce-123'
      }

      request = instance_double('Rack::Request')
      allow(request).to receive(:env).and_return(env)
      allow(request).to receive(:nil?).and_return(false)
      allow(request).to receive(:session).and_return(session)
      request
    end

    it 'includes CSP nonce when present' do
      expect(subject.view_vars['nonce']).to eq('test-nonce-123')
    end
  end

  context 'with global banner' do
    before do
      allow(OT).to receive('global_banner').and_return({
        type: 'info',
        message: 'System maintenance scheduled',
      },
                                                      )
    end

    it 'includes global banner when present' do
      view = described_class.new(rack_request)
      expect(view.serialized_data['global_banner']).to eq({
        type: 'info',
        message: 'System maintenance scheduled',
      },
                                                         )
    end
  end

  context 'with regions configuration' do
    let(:config) do
      super().merge(
        'features' => {
          'regions' => {
            'enabled' => true,
            'current_jurisdiction' => 'EU',
            'jurisdictions' => [
              {
                'identifier' => 'EU',
                'display_name' => 'European Union',
                'domain' => 'eu.example.com',
              },
            ],
          },
        },
      )
    end

    it 'includes regions config when enabled' do
      expect(subject.serialized_data['regions_enabled']).to be true
      expect(subject.serialized_data['regions']).to include(
        'enabled' => true,
        'current_jurisdiction' => 'EU',
      )
      # transform_regions includes identifier, domain, and i18n key
      expect(subject.serialized_data['regions']['jurisdictions']).to eq([
        {
          'identifier' => 'EU',
          'domain' => 'eu.example.com',
          'display_name_i18n_key' => 'web.regions.jurisdictions.eu.name',
        },
      ])
    end

    context 'when regions disabled' do
      let(:config) do
        super().merge(
          'features' => {
            'regions' => { 'enabled' => false },
          },
        )
      end

      it 'excludes regions data when disabled' do
        expect(subject.serialized_data['regions_enabled']).to be false
        expect(subject.serialized_data['regions']).to be_nil
      end
    end
  end

  context 'with required serialized_data keys' do
    let(:ensure_exist_keys) do
      %w[domains_enabled custid cust email customer_since]
    end

    it 'includes all required keys' do
      ensure_exist_keys.each do |key|
        expect(subject.serialized_data).to have_key(key),
          "Expected serialized_data to include #{key}"
      end
    end
  end

  context 'with locale configuration' do
    let(:default_config) do
      {
        'internationalization' => {
          'enabled' => true,
          'default_locale' => 'en',
          'fallback_locale' => {
            'fr-CA' => %w[fr_CA fr_FR en],
            'fr' => %w[fr_FR fr_CA en],
            'fr-*' => %w[fr_FR en],
            'default' => ['en'],
          },
          'locales' => %w[en fr_CA fr_FR],
        },
      }
    end

    # Test various locale scenarios
    shared_examples 'locale initialization' do |locale, expected|
      # Create subject on demand to use the current rack_request
      subject { described_class.new(rack_request) }

      let(:rack_request) do
        env = {
          'REMOTE_ADDR' => '127.0.0.1',
          'HTTP_HOST' => 'example.com',
          'rack.session' => {},
          'otto.locale' => locale,
          'otto.strategy_result' => strategy_result,
          'onetime.nonce' => nil
        }

        request = instance_double(Rack::Request)
        allow(request).to receive(:env).and_return(env)
        allow(request).to receive(:nil?).and_return(false)
        allow(request).to receive(:session).and_return({})
        request
      end

      it 'sets correct locale variables' do
        vars = subject.serialized_data
        expect(vars['locale']).to eq(expected[:locale])
      end
    end

    context 'with default locale' do
      it_behaves_like 'locale initialization', 'en', {
        locale: 'en',
        is_default: true,
      }
    end

    context 'with Canadian French locale' do
      it_behaves_like 'locale initialization', 'fr_CA', {
        locale: 'fr_CA',
        is_default: true,
      }
    end

    context 'with French locale' do
      it_behaves_like 'locale initialization', 'fr_FR', {
        locale: 'fr_FR',
        is_default: true,
      }
    end

    context 'with unsupported locale' do
      it_behaves_like 'locale initialization', 'es', {
        locale: 'es',
        is_default: true,
      }
    end

    context 'with missing locale (fallback to default)' do
      let(:rack_request) do
        # Do not include 'otto.locale' key - should fall back to OT.default_locale
        env = {
          'REMOTE_ADDR' => '127.0.0.1',
          'HTTP_HOST' => 'example.com',
          'rack.session' => session,
          'otto.strategy_result' => strategy_result,
          'onetime.nonce' => nil
        }

        request = instance_double(Rack::Request)
        allow(request).to receive(:env).and_return(env)
        allow(request).to receive(:nil?).and_return(false)
        allow(request).to receive(:session).and_return(session)
        request
      end

      it 'falls back to default locale' do
        vars = subject.serialized_data
        expect(vars['locale']).to eq('en')
      end
    end

    it 'runs I18nSerializer' do
      serialized = subject.serialized_data
      expect(serialized).to include('locale', 'default_locale', 'supported_locales')
    end
  end
end
