# apps/web/billing/docs_renderer.rb
#
# frozen_string_literal: true

require 'fileutils'
require 'yaml'
require_relative 'config'

module Billing
  # Pure YAML-to-Markdown renderer for the billing plan catalog.
  #
  # Has no dependency on Dry::CLI, OT, Familia, Redis, or any heavy gem.
  # Can be used standalone (scripts/billing-docs-generate.rb) or from the
  # CLI command (bin/ots billing catalog generate-docs).
  module DocsRenderer
    DEFAULT_OUTPUT = File.join('apps', 'web', 'billing', 'docs', 'plan-definitions.md').freeze

    # Generate docs and write to disk. Returns true on success, nil on skip.
    def self.generate_and_write(output_path: DEFAULT_OUTPUT)
      catalog_path = Billing::Config.config_path

      if catalog_path.nil? || !File.exist?(catalog_path.to_s)
        $stdout.puts '[billing catalog generate-docs] skipped: billing.yaml not configured'
        return nil
      end

      $stdout.puts "Loading catalog: #{catalog_path}"

      catalog      = Billing::Config.safe_load_config
      entitlements = Billing::Config.load_entitlements
      $stdout.puts "Loaded #{entitlements.size} entitlements from billing config"

      markdown = generate_markdown(catalog, entitlements)

      FileUtils.mkdir_p(File.dirname(output_path))
      File.write(output_path, markdown)

      $stdout.puts "Documentation generated: #{output_path}"
      $stdout.puts "   #{markdown.lines.count} lines, #{markdown.bytesize} bytes"
      true
    end

    def self.generate_markdown(catalog, entitlements)
      parts = []

      parts << generate_header(catalog)
      parts << generate_entitlements_section(entitlements) if entitlements&.any?
      parts << generate_plans_overview_table(catalog)
      parts << generate_plan_details(catalog, entitlements)
      parts << generate_stripe_metadata_section(catalog)
      parts << generate_validation_section

      parts.join("\n\n")
    end

    def self.generate_entitlements_section(entitlements)
      parts = ['## Entitlement Definitions', '']
      parts << 'Entitlements define features/permissions available in the billing system.'
      parts << 'Loaded from `etc/billing.yaml`.'
      parts << ''

      categories = entitlements.values.map { |ent| ent['category'] }.uniq.sort

      categories.each do |category|
        ents_in_category = entitlements.select { |_id, ent| ent['category'] == category }
        next if ents_in_category.empty?

        parts << "### #{category.capitalize}"
        parts << ''

        ents_in_category.each do |ent_id, ent_data|
          parts << "- **`#{ent_id}`**: #{ent_data['description']}"
        end

        parts << ''
      end

      parts.join("\n")
    end

    def self.generate_header(catalog)
      <<~MD
        # Plan Catalog Reference

        **Auto-generated from:** `etc/billing.yaml`
        **Schema Version:** #{catalog['schema_version']}

        ⚠️ **Do not edit this file directly.** This file is regenerated automatically:
        - Every `pnpm dev` (via the `predev` hook)
        - On demand: `pnpm run docs:billing:generate` or `bin/ots billing catalog generate-docs`

        Source of truth is `etc/billing.yaml`. Edit that file, then any of the
        above will refresh this doc. Stale committed output is treated as a
        drift bug — keep it synchronized.

        ## Overview

        This document describes the billing plan structure and entitlements for Onetime Secret. Plan definitions are stored in Stripe product metadata and cached in Redis via `Billing::Plan`.
      MD
    end

    def self.generate_plans_overview_table(catalog)
      plans = catalog['plans'] || {}

      rows = []
      rows << '## Plans Overview'
      rows << ''
      rows << '| Plan ID | Name | Tier | Tenancy | Region | Display Order | On Plans Page | Legacy |'
      rows << '|---------|------|------|---------|--------|---------------|---------------|--------|'

      plans.each do |plan_id, plan_data|
        show_icon   = plan_data['show_on_plans_page'] ? '✓' : '✗'
        legacy_icon = plan_data['legacy'] ? '⚠️' : ''
        rows << format(
          '| %s | %s | %s | %s | %s | %s | %s | %s |',
          plan_id,
          plan_data['name'],
          plan_data['tier'],
          plan_data['tenancy'],
          plan_data['region'],
          plan_data['display_order'],
          show_icon,
          legacy_icon,
        )
      end

      rows.join("\n")
    end

    def self.generate_plan_details(catalog, entitlements)
      plans            = catalog['plans'] || {}
      default_currency = catalog['currency'] || 'cad'

      sections = ['## Plan Details', '']

      plans.each do |plan_id, plan_data|
        sections << generate_plan_section(plan_id, plan_data, entitlements, default_currency)
        sections << ''
        sections << '---'
        sections << ''
      end

      sections.join("\n")
    end

    def self.generate_plan_section(plan_id, plan_data, _entitlements, default_currency)
      parts = []

      legacy_badge = plan_data['legacy'] ? ' ⚠️ **(Legacy)**' : ''
      parts << "### #{plan_data['name']} (`#{plan_id}`)#{legacy_badge}"
      parts << ''
      parts << plan_data['description'] if plan_data['description']
      parts << ''

      if plan_data['legacy'] && plan_data['grandfathered_until']
        parts << "**Grandfathered Until:** #{plan_data['grandfathered_until']}"
        parts << ''
      end

      parts << "**Tier:** #{plan_data['tier'] || 'N/A'}"
      parts << "**Tenancy:** #{plan_data['tenancy'] || 'N/A'}"
      parts << "**Region:** #{plan_data['region'] || 'N/A'}"
      parts << ''

      if plan_data['entitlements']&.any?
        parts << '**Entitlements:**'
        plan_data['entitlements'].each do |ent|
          parts << "- `#{ent}`"
        end
        parts << ''
      end

      if plan_data['limits']&.any?
        parts << '**Limits:**'
        parts << ''
        parts << '| Resource | Limit | Notes |'
        parts << '|----------|-------|-------|'

        plan_data['limits'].each do |resource, value|
          formatted_value = format_limit_value(value)
          notes           = limit_notes(resource, value)
          parts << "| #{resource} | #{formatted_value} | #{notes} |"
        end
        parts << ''
      end

      parts.concat(generate_pricing_section(plan_id, plan_data, default_currency))

      parts.join("\n")
    end

    def self.generate_pricing_section(plan_id, plan_data, default_currency)
      return ['**Pricing:** Free'] if plan_id == 'free_v1'
      return [] unless plan_data['prices']&.any?

      lines = ['**Pricing:**']
      plan_data['prices'].each do |price|
        amount_dollars = (price['amount'] / 100.0).round(2)
        currency_upper = (price['currency'] || default_currency).upcase
        interval_label = price['interval'] == 'month' ? 'Monthly' : 'Annual'
        lines << "- #{interval_label}: $#{amount_dollars} #{currency_upper}"
      end
      lines
    end

    def self.format_limit_value(value)
      case value
      when -1
        '∞ (unlimited)'
      when nil
        'TBD'
      else
        value.to_s
      end
    end

    LIMIT_NOTE_FORMATTERS = {
      'secret_lifetime' => ->(value) { value && value.to_i > 0 ? "#{value.to_i / 86_400} days" : '' },
      'teams' => ->(value) { value&.to_i == 0 ? 'No team access' : '' },
      'total_members_per_org' => ->(value) { value&.to_i == 1 ? 'Individual only' : '' },
    }.freeze

    def self.limit_notes(resource, value)
      formatter = LIMIT_NOTE_FORMATTERS[resource]
      formatter ? formatter.call(value) : ''
    end

    def self.generate_stripe_metadata_section(catalog)
      schema = catalog['stripe_metadata_schema'] || {}

      parts = ['## Stripe Product Configuration', '']
      parts << 'Each Stripe product must include specific metadata fields to be recognized by the billing system.'
      parts << ''

      if schema['required']
        parts << '### Required Metadata Fields'
        parts << ''
        parts << '```json'
        parts << '{'

        schema['required'].each_with_index do |entry, idx|
          key, desc = entry.is_a?(Hash) ? entry.first : [entry, '']
          comma     = idx < schema['required'].size - 1 ? ',' : ''
          parts << "  \"#{key}\": \"#{desc}\"#{comma}"
        end

        parts << '}'
        parts << '```'
        parts << ''
      end

      if schema['optional']
        parts << '### Optional Metadata Fields'
        parts << ''
        parts << '```json'
        parts << '{'

        schema['optional'].each_with_index do |entry, idx|
          key, desc = entry.is_a?(Hash) ? entry.first : [entry, '']
          comma     = idx < schema['optional'].size - 1 ? ',' : ''
          parts << "  \"#{key}\": \"#{desc}\"#{comma}"
        end

        parts << '}'
        parts << '```'
      end

      parts.join("\n")
    end

    def self.generate_validation_section
      <<~MD
        ## Validation and Sync

        ### Validate Catalog Structure

        Validate YAML structure and compare with Stripe:

        ```bash
        bin/ots billing catalog validate
        bin/ots billing catalog validate --catalog-only  # Skip Stripe comparison
        bin/ots billing catalog validate --strict        # Fail on warnings
        ```

        ### Sync Plans from Stripe

        After configuring products in Stripe, sync to local Redis cache:

        ```bash
        bin/ots billing sync
        bin/ots billing sync --clear  # Clear cache first
        ```

        Only products with all required metadata fields, at least one recurring price, and `app: "onetimesecret"` will be synced.

        ### View Cached Plans

        ```bash
        bin/ots billing plans
        ```

        ## Setup Workflow

        1. **Edit catalog:** Modify `etc/billing.yaml`
        2. **Validate:** `bin/ots billing catalog validate --catalog-only`
        3. **Create/update in Stripe:** `./scripts/setup_stripe_plans.sh --update`
        4. **Verify in Stripe:** Check Stripe Dashboard
        5. **Sync to cache:** `bin/ots billing sync`
        6. **Update docs:** `bin/ots billing catalog generate-docs`
        7. **Commit:** Commit both YAML and generated docs
      MD
    end
  end
end
