#!/bin/bash

# Wrapper to repair all locale directories
#
# Usage: ./harmonize-all-locale-files [-q quiet] [-f filename-only] [-v verbose]
#
# Options:
#   -q: Suppress all output
#   -f: Only output filenames of failed repairs
#   -v: Show verbose repair output
#   -c: copy values from base file
#
# Exit: 0 if all repairs succeed, 1 if any fail

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

EXIT_CODE=0
for locale_dir in src/locales/*/; do
  [ ! -d "$locale_dir" ] && continue

  locale_name=$(basename "$locale_dir")
  [ "$locale_name" = "en" ] && continue
  echo "-> $locale_name"
  "$SCRIPT_DIR/harmonize-locale-file.py" "$@" "$locale_name" || EXIT_CODE=1
done
exit $EXIT_CODE
