# .github/workflows/config.yml

name: Validate YAML config
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - 'main'
      - 'fix/*'
      - 'feature/*'
      - 'rel/*'

  pull_request:
    branches:
      - main
      - develop
      - feature/*

  # Manual trigger option for debugging
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Enable tmate debugging for secure troubleshooting'
        required: false
        default: false

jobs:
  config-validation:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@7d3497fd78c07c0d84ebafa58d8dac60cd1f0763 # v1.199.0
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 10.10.0

      - name: Install Node dependencies
        run: pnpm install

      - name: Generate JSON schemas
        run: pnpm run schema:generate

      - name: Validate example config
        run: pnpm run schema:validate

      - name: Validate test config
        continue-on-error: true
        run: |
          echo "Validating test configuration (may have intentional errors)..."
          bin/ots validate tests/unit/ruby/config.test.yaml || true
