# .github/workflows/vue-types.yml

name: Vue Type Check

# This GitHub Action runs Vue.js type checking using vue-tsc
#
#  1. It triggers on pushes to fix/* and rel/* branches, pull requests to
#     main/develop/feature/* branches, and manual workflow dispatch.
#  2. It uses Ubuntu as the runner environment.
#  3. It checks out your code and sets up Node.js version 22.
#  4. It installs pnpm version 10, as specified in your `package.json`.
#  5. It installs the project dependencies using `pnpm install`.
#  6. It runs type checking using the `pnpm run type-check` command, which
#     corresponds to the `"type-check": "vue-tsc --noEmit"` script in your `package.json`.
#
#  This action ensures that your Vue TypeScript types are checked on every push
#  to relevant branches and for every pull request.
#
#  For more information on GitHub Actions, you can refer to the [official
#  documentation](https://docs.github.com/en/actions).

on:
  push:
    branches:
      - fix/*
      - rel/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

permissions:
  contents: read

jobs:
  type-check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run type check
        run: pnpm run type-check
        continue-on-error: false

      - name: Run type check tests
        run: pnpm run type-check:tests
        continue-on-error: true
