name: Vue Tests

# This GitHub Action does the following:
#
#  1. It triggers on pushes to the `main` branch and on pull requests to
#     the `main` branch.
#  2. It uses Ubuntu as the runner environment.
#  3. It checks out your code and sets up Node.js version 18.
#  4. It installs pnpm version 9, as specified in your `package.json`.
#  5. It installs the project dependencies using `pnpm install`.
#  6. It runs the tests using the `pnpm test` command, which corresponds to
#     the `"test": "vitest run"` script in your `package.json`.
#  7. It runs a type check using the `pnpm run type-check` command, which
#     corresponds to the `"type-check": "vue-tsc --noEmit"` script in your
#     `package.json`.
#
#  This action will ensure that your tests are run and type checking is
#  performed on every push to the main branch and for every pull request.
#
#  Note that this action uses Vitest for running tests, as specified in
#  your `package.json`. If you need to add any specific Vite or Vue
#  configuration for testing, you can do so in your `vite.config.ts` file.
#
#  For more information on GitHub Actions, you can refer to the [official
#  documentation](https://docs.github.com/en/actions).

on:
  push:
    branches:
      - fix/*
      - rel/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Run type check
        run: pnpm run type-check
        continue-on-error: false

      - name: Run tests
        run: pnpm test
        continue-on-error: true
