# .github/workflows/welcome-contributor.yml
---
# Onetime Secret Ops
#
# Welcomes first-time contributors when they open their first PR.
#
# Documentation:
# https://github.com/actions/first-interaction
#
# ## Workflow Guidance
#
# - Use existing tags, don't create new tags, but suggestions always welcome.
# - Keep any Issue or PR templates minimal.
# - Use separate github workflows for triggers that are not copacetic: for
#   example, something that runs when an issue created shouldn't run when a
#   PR is created as well; or workflows that are meant to run on different
#   schedules.
#
name: Welcome Contributor
on:
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Let's play it cool, Tiny Elvis
        run: sleep 180 # 3 minutes

      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          repo-token: ${{ secrets.MAINTAINER_PAT }}

          pr-message: |
            Thanks for the PR. I can usually review it within a day or two. Feel free to @ me and I'll respond sooner if I can.

            Heads up: there's a fair amount of automated review activity on this repo (linting, security checks, etc). Take advantage of the feedback if it's useful, but no need to address everything. I'll sort it out during review.
